# Generated by Django 5.2.9 on 2026-01-04 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ชื่อแผนก"
                    ),
                ),
            ],
            options={
                "verbose_name": "1. แผนก",
                "verbose_name_plural": "1. จัดการแผนก (Departments)",
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ชื่อตำแหน่ง"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.department",
                        verbose_name="สังกัดแผนก",
                    ),
                ),
            ],
            options={
                "verbose_name": "2. ตำแหน่ง",
                "verbose_name_plural": "2. จัดการตำแหน่ง (Positions)",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="รหัสพนักงาน"
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="ชื่อจริง")),
                ("last_name", models.CharField(max_length=100, verbose_name="นามสกุล")),
                (
                    "nickname",
                    models.CharField(blank=True, max_length=50, verbose_name="ชื่อเล่น"),
                ),
                (
                    "salary",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="เงินเดือน",
                    ),
                ),
                (
                    "joined_date",
                    models.DateField(blank=True, null=True, verbose_name="วันที่เริ่มงาน"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="เบอร์โทร"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="อีเมล"),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="employees/",
                        verbose_name="รูปถ่าย",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="สถานะพนักงาน (Active)"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="บัญชีผู้ใช้ (Login)",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.position",
                        verbose_name="ตำแหน่ง",
                    ),
                ),
            ],
            options={
                "verbose_name": "3. พนักงาน",
                "verbose_name_plural": "3. รายชื่อพนักงาน (Employees)",
            },
        ),
    ]
