# Generated by Django 5.2.9 on 2026-01-05 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="ประเภทพนักงาน")),
            ],
        ),
        migrations.AlterModelOptions(
            name="department",
            options={},
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={"ordering": ["emp_id"], "verbose_name": "พนักงาน"},
        ),
        migrations.AlterModelOptions(
            name="position",
            options={},
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="employee_id",
            new_name="emp_id",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="email",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="joined_date",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="picture",
        ),
        migrations.RemoveField(
            model_name="position",
            name="name",
        ),
        migrations.AddField(
            model_name="employee",
            name="address",
            field=models.TextField(blank=True, verbose_name="ที่อยู่ปัจจุบัน"),
        ),
        migrations.AddField(
            model_name="employee",
            name="bank_account_no",
            field=models.CharField(blank=True, max_length=20, verbose_name="เลขที่บัญชี"),
        ),
        migrations.AddField(
            model_name="employee",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="วันเกิด"),
        ),
        migrations.AddField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hr.department",
                verbose_name="แผนก",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                choices=[("M", "ชาย"), ("F", "หญิง")],
                default="M",
                max_length=1,
                verbose_name="เพศ",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="id_card",
            field=models.CharField(
                blank=True, max_length=13, verbose_name="เลขบัตรประชาชน"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="photo",
            field=models.ImageField(
                blank=True, upload_to="employees/", verbose_name="รูปถ่าย"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="prefix",
            field=models.CharField(default="คุณ", max_length=20, verbose_name="คำนำหน้า"),
        ),
        migrations.AddField(
            model_name="employee",
            name="resign_date",
            field=models.DateField(blank=True, null=True, verbose_name="วันที่ลาออก"),
        ),
        migrations.AddField(
            model_name="employee",
            name="social_security_id",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="เลขประกันสังคม"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="start_date",
            field=models.DateField(default="2026-01-01", verbose_name="วันที่เริ่มงาน"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="status",
            field=models.CharField(
                choices=[
                    ("probation", "ทดลองงาน"),
                    ("permanent", "พนักงานประจำ"),
                    ("resigned", "ลาออก"),
                ],
                default="probation",
                max_length=20,
                verbose_name="สถานะภาพ",
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="title",
            field=models.CharField(default=1, max_length=100, verbose_name="ชื่อตำแหน่ง"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=100, verbose_name="ชื่อแผนก"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="ชื่อจริง (ไทย)"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="นามสกุล (ไทย)"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="เบอร์โทรศัพท์"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="salary",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="เงินเดือนปัจจุบัน"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User Account",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="emp_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hr.employeetype",
                verbose_name="ประเภทการจ้าง",
            ),
        ),
    ]
