# Generated by Django 5.2.9 on 2026-01-05 18:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0002_employeetype_alter_department_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="start_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="วันที่เริ่มงาน"
            ),
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("sick", "ลาป่วย"),
                            ("business", "ลากิจ"),
                            ("vacation", "ลาพักร้อน"),
                            ("other", "อื่นๆ"),
                        ],
                        max_length=20,
                        verbose_name="ประเภทการลา",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="วันที่เริ่มลา")),
                ("end_date", models.DateField(verbose_name="ถึงวันที่")),
                ("reason", models.TextField(verbose_name="เหตุผลการลา")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "รออนุมัติ"),
                            ("approved", "อนุมัติแล้ว"),
                            ("rejected", "ไม่อนุมัติ"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="สถานะ",
                    ),
                ),
                (
                    "approved_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="วันที่อนุมัติ"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้อนุมัติ",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.employee",
                        verbose_name="พนักงาน",
                    ),
                ),
            ],
            options={
                "verbose_name": "ใบลา",
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="วันที่")),
                (
                    "time_in",
                    models.TimeField(blank=True, null=True, verbose_name="เวลาเข้างาน"),
                ),
                (
                    "time_out",
                    models.TimeField(blank=True, null=True, verbose_name="เวลาออกงาน"),
                ),
                (
                    "total_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="ชั่วโมงทำงานรวม",
                    ),
                ),
                ("is_late", models.BooleanField(default=False, verbose_name="มาสาย")),
                (
                    "is_overtime",
                    models.BooleanField(default=False, verbose_name="มี OT"),
                ),
                ("note", models.TextField(blank=True, verbose_name="หมายเหตุ")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.employee",
                        verbose_name="พนักงาน",
                    ),
                ),
            ],
            options={
                "verbose_name": "บันทึกเวลาทำงาน",
                "unique_together": {("employee", "date")},
            },
        ),
    ]
