# Generated by Django 5.2.9 on 2026-01-05 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0003_alter_employee_start_date_leaverequest_attendance"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={
                "verbose_name": "บันทึกเวลาทำงาน",
                "verbose_name_plural": "บันทึกเวลาทำงาน",
            },
        ),
        migrations.AlterModelOptions(
            name="department",
            options={"verbose_name": "แผนก", "verbose_name_plural": "ข้อมูลแผนก"},
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={
                "ordering": ["emp_id"],
                "verbose_name": "พนักงาน",
                "verbose_name_plural": "ข้อมูลพนักงาน",
            },
        ),
        migrations.AlterModelOptions(
            name="employeetype",
            options={
                "verbose_name": "ประเภทพนักงาน",
                "verbose_name_plural": "ข้อมูลประเภทพนักงาน",
            },
        ),
        migrations.AlterModelOptions(
            name="leaverequest",
            options={"verbose_name": "ใบลา", "verbose_name_plural": "รายการใบลา"},
        ),
        migrations.AlterModelOptions(
            name="position",
            options={"verbose_name": "ตำแหน่ง", "verbose_name_plural": "ข้อมูลตำแหน่ง"},
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(default=2026, verbose_name="ปี ค.ศ.")),
                (
                    "month",
                    models.IntegerField(
                        choices=[
                            (1, "มกราคม"),
                            (2, "กุมภาพันธ์"),
                            (3, "มีนาคม"),
                            (4, "เมษายน"),
                            (5, "พฤษภาคม"),
                            (6, "มิถุนายน"),
                            (7, "กรกฎาคม"),
                            (8, "สิงหาคม"),
                            (9, "กันยายน"),
                            (10, "ตุลาคม"),
                            (11, "พฤศจิกายน"),
                            (12, "ธันวาคม"),
                        ],
                        verbose_name="เดือน",
                    ),
                ),
                (
                    "base_salary",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="เงินเดือน",
                    ),
                ),
                (
                    "ot_pay",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="ค่าล่วงเวลา (OT)",
                    ),
                ),
                (
                    "bonus",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="โบนัส/เบี้ยขยัน",
                    ),
                ),
                (
                    "other_income",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="รายได้อื่นๆ",
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="ภาษี ณ ที่จ่าย",
                    ),
                ),
                (
                    "social_security",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="ประกันสังคม",
                    ),
                ),
                (
                    "leave_deduction",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="หักขาด/ลา/สาย",
                    ),
                ),
                (
                    "other_deduction",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="หักอื่นๆ"
                    ),
                ),
                (
                    "net_salary",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="เงินได้สุทธิ",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "ร่าง (ยังไม่ยืนยัน)"),
                            ("published", "อนุมัติ (พนักงานเห็นแล้ว)"),
                            ("paid", "จ่ายเงินแล้ว"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="สถานะ",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(blank=True, null=True, verbose_name="วันที่โอนเงิน"),
                ),
                ("note", models.TextField(blank=True, verbose_name="หมายเหตุ")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.employee",
                        verbose_name="พนักงาน",
                    ),
                ),
            ],
            options={
                "verbose_name": "สลิปเงินเดือน",
                "verbose_name_plural": "จัดการสลิปเงินเดือน",
                "unique_together": {("employee", "year", "month")},
            },
        ),
    ]
