# Generated by Django 5.1.3 on 2026-01-08 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0004_alter_attendance_options_alter_department_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="bank_account",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="เลขบัญชี (รับคอมมิชชั่น)"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="bank_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ธนาคาร (รับคอมมิชชั่น)"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="business_rank",
            field=models.CharField(
                choices=[
                    ("member", "Member (สมาชิกทั่วไป)"),
                    ("supervisor", "Supervisor (หัวหน้าทีม)"),
                    ("manager", "Manager (ผู้จัดการทีม)"),
                    ("director", "Director (ผู้อำนวยการ)"),
                ],
                default="member",
                max_length=20,
                verbose_name="ระดับธุรกิจ",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="ค่าคอมมิชชั่น (%)",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="introducer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="downlines",
                to="hr.employee",
                verbose_name="ผู้แนะนำ (Upline)",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="bank_account_no",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="เลขที่บัญชี (เงินเดือน)"
            ),
        ),
    ]
