# Generated by Django 5.1.3 on 2026-01-08 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0005_employee_bank_account_employee_bank_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommissionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField(verbose_name="ชั้นที่ (Level)")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="จำนวนเงิน (บาท)"
                    ),
                ),
                (
                    "sale_ref_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="อ้างอิงเลขที่บิล"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่ได้รับ"),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commissions_received",
                        to="hr.employee",
                        verbose_name="ผู้รับเงิน",
                    ),
                ),
                (
                    "source_employee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.employee",
                        verbose_name="จากยอดขายของ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ประวัติค่าคอมมิชชั่น",
                "verbose_name_plural": "ประวัติค่าคอมมิชชั่น",
            },
        ),
    ]
