# Generated by Django 5.1.3 on 2026-01-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0006_commissionlog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={"verbose_name_plural": "บันทึกเวลาทำงาน"},
        ),
        migrations.AlterModelOptions(
            name="commissionlog",
            options={"verbose_name_plural": "ประวัติค่าคอมมิชชั่น"},
        ),
        migrations.AlterModelOptions(
            name="department",
            options={"verbose_name_plural": "ข้อมูลแผนก"},
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={"verbose_name_plural": "ข้อมูลพนักงาน"},
        ),
        migrations.AlterModelOptions(
            name="employeetype",
            options={"verbose_name_plural": "ข้อมูลประเภทพนักงาน"},
        ),
        migrations.AlterModelOptions(
            name="leaverequest",
            options={"verbose_name_plural": "รายการใบลา"},
        ),
        migrations.AlterModelOptions(
            name="payslip",
            options={"verbose_name_plural": "จัดการสลิปเงินเดือน"},
        ),
        migrations.AlterModelOptions(
            name="position",
            options={"verbose_name_plural": "ข้อมูลตำแหน่ง"},
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="payslip",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="employee",
            name="signature",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="signatures/",
                verbose_name="รูปลายเซ็นต์ (สำหรับอนุมัติ)",
            ),
        ),
        migrations.AlterField(
            model_name="commissionlog",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="จำนวนเงิน"
            ),
        ),
        migrations.AlterField(
            model_name="commissionlog",
            name="level",
            field=models.IntegerField(verbose_name="ชั้นที่"),
        ),
        migrations.AlterField(
            model_name="commissionlog",
            name="sale_ref_id",
            field=models.CharField(blank=True, max_length=50, verbose_name="อ้างอิง"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="business_rank",
            field=models.CharField(
                choices=[
                    ("member", "Member"),
                    ("supervisor", "Supervisor"),
                    ("manager", "Manager"),
                    ("director", "Director"),
                ],
                default="member",
                max_length=20,
                verbose_name="ระดับธุรกิจ",
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="bonus",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="โบนัส"
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="leave_deduction",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="หักลา"
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="net_salary",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="สุทธิ"
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="ot_pay",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="OT"
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="payment_date",
            field=models.DateField(blank=True, null=True, verbose_name="วันที่โอน"),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="status",
            field=models.CharField(
                choices=[("draft", "ร่าง"), ("published", "อนุมัติ"), ("paid", "จ่ายแล้ว")],
                default="draft",
                max_length=20,
                verbose_name="สถานะ",
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="tax",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="ภาษี"
            ),
        ),
    ]
