# Generated by Django 5.1.3 on 2026-04-01 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0007_alter_attendance_options_alter_commissionlog_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ชื่อกลุ่ม/ทีม"
                    ),
                ),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("EXECUTIVE", "กลุ่มผู้บริหาร"),
                            ("TEAM", "กลุ่มทำงาน"),
                            ("INDEPENDENT", "พนักงานขายอิสระ"),
                        ],
                        max_length=20,
                        verbose_name="ประเภทกลุ่ม",
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="ค่าคอมฯจากยอดขาย (%)",
                    ),
                ),
                (
                    "share_leader",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="ส่วนแบ่งหัวหน้า (%)",
                    ),
                ),
                (
                    "share_level1",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="ส่วนแบ่งระดับ 1 (%)",
                    ),
                ),
                (
                    "share_level2",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="ส่วนแบ่งระดับ 2 (%)",
                    ),
                ),
                (
                    "share_fund",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="เข้ากองทุนกลุ่ม (%)",
                    ),
                ),
                (
                    "fund_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="ยอดเงินกองทุนคงเหลือ",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "จัดการกลุ่มขายและกองทุน",
            },
        ),
        migrations.AlterModelOptions(
            name="commissionlog",
            options={"verbose_name_plural": "ประวัติค่าคอมมิชชั่นบุคคล"},
        ),
        migrations.AddField(
            model_name="employee",
            name="group_role",
            field=models.CharField(
                choices=[
                    ("LEADER", "หัวหน้ากลุ่ม"),
                    ("LEVEL1", "พนักงานระดับ 1"),
                    ("LEVEL2", "พนักงานระดับ 2"),
                    ("MEMBER", "สมาชิก/อิสระ"),
                ],
                default="MEMBER",
                max_length=20,
                verbose_name="บทบาทในทีม",
            ),
        ),
        migrations.AlterField(
            model_name="commissionlog",
            name="level",
            field=models.IntegerField(default=1, verbose_name="ชั้นที่"),
        ),
        migrations.AlterField(
            model_name="commissionlog",
            name="sale_ref_id",
            field=models.CharField(blank=True, max_length=50, verbose_name="อ้างอิงบิล"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="business_rank",
            field=models.CharField(
                choices=[
                    ("member", "Member"),
                    ("supervisor", "Supervisor"),
                    ("manager", "Manager"),
                    ("director", "Director"),
                ],
                default="member",
                max_length=20,
                verbose_name="ระดับธุรกิจเก่า",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="เรทคอมฯส่วนตัวเดิม",
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="bonus",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="โบนัส/ค่าคอมมิชชัน",
            ),
        ),
        migrations.CreateModel(
            name="CompanySalesTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="ปี ค.ศ.")),
                ("month", models.IntegerField(verbose_name="เดือน")),
                (
                    "target_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=50000000.0,
                        max_digits=15,
                        verbose_name="เป้าหมายยอดขายบริษัท",
                    ),
                ),
                (
                    "current_sales",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="ยอดขายปัจจุบัน",
                    ),
                ),
                (
                    "is_unlocked",
                    models.BooleanField(
                        default=False, verbose_name="บรรลุเป้าหมาย (ปลดล็อคคอมผู้บริหารแล้ว)"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "เป้าหมายยอดขายบริษัท (ภารกิจผู้บริหาร)",
                "unique_together": {("year", "month")},
            },
        ),
        migrations.CreateModel(
            name="FundWithdrawalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="จำนวนเงิน"
                    ),
                ),
                ("reason", models.TextField(verbose_name="วัตถุประสงค์การใช้เงิน")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("VOTING", "รอสมาชิกในกลุ่มยืนยัน"),
                            ("PENDING", "รอผู้บริหารอนุมัติ"),
                            ("APPROVED", "อนุมัติแล้ว"),
                            ("REJECTED", "ไม่อนุมัติ"),
                        ],
                        default="VOTING",
                        max_length=20,
                        verbose_name="สถานะ",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้บริหารที่อนุมัติ",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fund_requests",
                        to="hr.employee",
                        verbose_name="พนักงานผู้ขอเบิก",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.salesgroup",
                        verbose_name="กลุ่มที่ขอเบิก",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "คำร้องขอเบิกเงินกองทุนกลุ่ม",
            },
        ),
        migrations.CreateModel(
            name="FundWithdrawalVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(default=False, verbose_name="กดยืนยันแล้ว"),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="hr.fundwithdrawalrequest",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.employee",
                        verbose_name="ผู้ลงมติ",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FundTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("IN", "รายรับ (คอมมิชชัน)"), ("OUT", "รายจ่าย (เบิกใช้)")],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="hr.salesgroup",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employee",
            name="sales_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="hr.salesgroup",
                verbose_name="สังกัดทีมขาย",
            ),
        ),
    ]
