# Generated by Django 5.1.3 on 2026-04-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0008_salesgroup_alter_commissionlog_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesgroup",
            name="share_exec1",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="ส่วนแบ่งผู้บริหารคนที่ 1 (%)",
            ),
        ),
        migrations.AddField(
            model_name="salesgroup",
            name="share_exec2",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="ส่วนแบ่งผู้บริหารคนที่ 2 (%)",
            ),
        ),
        migrations.AddField(
            model_name="salesgroup",
            name="share_exec3",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="ส่วนแบ่งผู้บริหารคนที่ 3 (%)",
            ),
        ),
        migrations.AddField(
            model_name="salesgroup",
            name="share_exec4",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="ส่วนแบ่งผู้บริหารคนที่ 4 (%)",
            ),
        ),
        migrations.AddField(
            model_name="salesgroup",
            name="share_exec5",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="ส่วนแบ่งผู้บริหารคนที่ 5 (%)",
            ),
        ),
    ]
