# Generated by Django 5.1.3 on 2026-04-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0009_salesgroup_share_exec1_salesgroup_share_exec2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="latitude",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="ละติจูด (Latitude)"
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="longitude",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="ลองจิจูด (Longitude)"
            ),
        ),
    ]
