# Generated by Django 5.1.3 on 2026-04-13 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0010_attendance_latitude_attendance_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_departments",
                to="hr.department",
                verbose_name="สังกัดแผนกหลัก (ถ้ามี)",
            ),
        ),
    ]
