# Generated by Django 5.1.3 on 2026-04-19 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0011_department_parent"),
        ("manufacturing", "0020_productionorder_rework_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="production_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manufacturing.productionteam",
                verbose_name="สังกัดทีมช่างผลิต",
            ),
        ),
    ]
