# Generated by Django 5.1.3 on 2026-05-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0012_employee_production_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesgroup",
            name="flat_rate_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="ค่าตอบแทนเหมาจ่าย (บาท/งาน)",
            ),
        ),
    ]
