# Generated by Django 4.2.30 on 2026-08-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0013_salesgroup_flat_rate_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="approval_authority",
            field=models.TextField(
                blank=True, null=True, verbose_name="อำนาจการอนุมัติ (Approval Authority)"
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="รายละเอียดงาน (Job Description)"
            ),
        ),
    ]
