# Generated by Django 5.2.9 on 2026-01-04 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("master_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ชื่อหมวดหมู่"
                    ),
                ),
            ],
            options={
                "verbose_name": "1. หมวดหมู่สินค้า",
                "verbose_name_plural": "1. จัดการหมวดหมู่ (Categories)",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="รหัสสินค้า/SKU"
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="บาร์โค้ด"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="ชื่อสินค้า")),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="ราคาทุน",
                    ),
                ),
                (
                    "sell_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="ราคาขาย",
                    ),
                ),
                (
                    "stock_qty",
                    models.IntegerField(default=0, verbose_name="จำนวนคงเหลือ"),
                ),
                (
                    "min_level",
                    models.IntegerField(default=5, verbose_name="จุดสั่งซื้อ (Low Stock)"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/",
                        verbose_name="รูปสินค้า",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="เปิดขาย")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.category",
                        verbose_name="หมวดหมู่",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="master_data.supplier",
                        verbose_name="ซัพพลายเออร์หลัก",
                    ),
                ),
            ],
            options={
                "verbose_name": "2. รายการสินค้า",
                "verbose_name_plural": "2. จัดการสินค้า (Products)",
            },
        ),
    ]
