# Generated by Django 5.1.3 on 2026-01-19 15:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("IN", "รับเข้า (ซื้อ/ผลิตเสร็จ)"),
                            ("OUT", "เบิกออก (ขาย/เสียหาย)"),
                            ("PRODUCTION", "เบิกไปผลิต"),
                        ],
                        max_length=20,
                        verbose_name="ประเภทรายการ",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="จำนวน")),
                (
                    "reference_doc",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="อ้างอิงเอกสาร (PO/SO)"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="หมายเหตุ")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="วันที่ทำรายการ"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ทำรายการ",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                        verbose_name="สินค้า",
                    ),
                ),
            ],
            options={
                "verbose_name": "3. ประวัติสต็อก",
                "verbose_name_plural": "3. ประวัติการเคลื่อนไหว (Stock Movements)",
            },
        ),
    ]
