# Generated by Django 5.1.3 on 2026-01-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_stockmovement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="code",
            field=models.CharField(
                blank=True, max_length=50, unique=True, verbose_name="รหัสสินค้า/SKU"
            ),
        ),
    ]
