# Generated by Django 5.1.3 on 2026-01-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_product_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[("FG", "สินค้าสำเร็จรูป (พร้อมขาย)"), ("RM", "วัตถุดิบ (สำหรับผลิต)")],
                default="FG",
                max_length=2,
                verbose_name="ประเภทสินค้า",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="เปิดใช้งาน"),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="reference_doc",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="อ้างอิงเอกสาร"
            ),
        ),
    ]
