# Generated by Django 5.1.3 on 2026-01-21 17:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_product_product_type_alter_product_is_active_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stockmovement",
            options={
                "verbose_name": "4. รายการสินค้าในเอกสาร",
                "verbose_name_plural": "4. รายการเคลื่อนไหว (Details)",
            },
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="เวลาบันทึก"
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[("IN", "เข้า"), ("OUT", "ออก")],
                max_length=10,
                verbose_name="ประเภท",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="reference_doc",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="อ้างอิงเดิม (Legacy)"
            ),
        ),
        migrations.CreateModel(
            name="InventoryDoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_no",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="เลขที่เอกสาร",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("GR", "ใบรับสินค้า (Goods Receipt)"),
                            ("GI", "ใบเบิกสินค้า (Goods Issue)"),
                        ],
                        max_length=2,
                        verbose_name="ประเภทเอกสาร",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="อ้างอิง (PO/Job No.)"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="หมายเหตุ")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="วันที่เอกสาร"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ทำรายการ",
                    ),
                ),
            ],
            options={
                "verbose_name": "3. เอกสารคลังสินค้า",
                "verbose_name_plural": "3. เอกสารคลังสินค้า (Docs)",
            },
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="doc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movements",
                to="inventory.inventorydoc",
                verbose_name="เลขที่เอกสาร",
            ),
        ),
    ]
