# Generated by Django 5.1.3 on 2026-01-22 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_alter_stockmovement_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinishedGood",
            fields=[],
            options={
                "verbose_name": "2.1 สินค้าสำเร็จรูป (FG)",
                "verbose_name_plural": "2.1 สินค้าสำเร็จรูป (FG)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("inventory.product",),
        ),
        migrations.CreateModel(
            name="RawMaterial",
            fields=[],
            options={
                "verbose_name": "2.2 วัตถุดิบ (RM)",
                "verbose_name_plural": "2.2 วัตถุดิบ (RM)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("inventory.product",),
        ),
    ]
