# Generated by Django 5.1.3 on 2026-03-02 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_finishedgood_rawmaterial"),
        ("purchasing", "0003_purchaseorder_ppo_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorydoc",
            name="po_reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receipt_docs",
                to="purchasing.purchaseorder",
                verbose_name="อ้างอิงใบสั่งซื้อ (PO)",
            ),
        ),
        migrations.AlterField(
            model_name="inventorydoc",
            name="reference",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="อ้างอิงอื่นๆ (เช่น ทะเบียนรถ, ใบส่งของ)",
            ),
        ),
    ]
