# Generated by Django 5.1.3 on 2026-03-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_inventorydoc_po_reference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="standard_blueprint",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="standard_blueprints/",
                verbose_name="ไฟล์แบบแปลนมาตรฐาน (PDF/รูปภาพ)",
            ),
        ),
    ]
