# Generated by Django 5.1.3 on 2026-04-04 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_product_standard_blueprint"),
        ("master_data", "0013_companyinfo_seal"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSupplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier_part_no",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="รหัสสินค้าของร้านค้า"
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="ราคาทุน (จากร้านนี้)",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="เป็นร้านค้าหลัก"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multi_suppliers",
                        to="inventory.product",
                        verbose_name="วัตถุดิบ/สินค้า",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplied_products",
                        to="master_data.supplier",
                        verbose_name="ร้านค้า",
                    ),
                ),
            ],
            options={
                "verbose_name": "2.3 รายชื่อร้านค้าสำหรับสินค้า",
                "verbose_name_plural": "2.3 ร้านค้าแบบ Multi-source",
                "unique_together": {("product", "supplier")},
            },
        ),
    ]
