# Generated by Django 5.1.3 on 2026-04-05 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_productsupplier"),
        ("master_data", "0014_shippingrate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="master_data.supplier",
                verbose_name="ซัพพลายเออร์หลัก (Legacy)",
            ),
        ),
        migrations.CreateModel(
            name="SupplierPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="ราคาเดิม"
                    ),
                ),
                (
                    "new_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="ราคาใหม่"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่อัปเดต"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_histories",
                        to="inventory.product",
                        verbose_name="วัตถุดิบ",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master_data.supplier",
                        verbose_name="ร้านค้า",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้แก้ไข",
                    ),
                ),
            ],
            options={
                "verbose_name": "2.4 ประวัติราคาซื้อ",
                "verbose_name_plural": "2.4 ประวัติราคาจากซัพพลายเออร์",
            },
        ),
    ]
