# Generated by Django 5.1.3 on 2026-04-05 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_alter_product_supplier_supplierpricehistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawMaterialCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ชื่อหมวดหมู่วัตถุดิบ (แผนก)"
                    ),
                ),
            ],
            options={
                "verbose_name": "1.1 แผนกวัตถุดิบ",
                "verbose_name_plural": "1.1 จัดการแผนกวัตถุดิบ",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.category",
                verbose_name="หมวดหมู่สินค้า",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="rm_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.rawmaterialcategory",
                verbose_name="หมวดหมู่วัตถุดิบ (แผนก)",
            ),
        ),
    ]
