# Generated by Django 5.1.3 on 2026-04-13 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_rawmaterialcategory_alter_product_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="finishedgood",
            options={
                "verbose_name": "2.1 แคตตาล็อกสินค้าพร้อมขาย (สำหรับฝ่ายขาย)",
                "verbose_name_plural": "2.1 แคตตาล็อกสินค้าพร้อมขาย (สำหรับฝ่ายขาย)",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "verbose_name": "2. จัดการคลังสินค้า/วัตถุดิบ (Master)",
                "verbose_name_plural": "2. จัดการคลังสินค้า/วัตถุดิบ (Master)",
            },
        ),
    ]
