# Generated by Django 5.1.3 on 2026-04-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_alter_finishedgood_options_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="หน่วยนับ"
            ),
        ),
    ]
