# Generated by Django 5.1.3 on 2026-04-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_product_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="min_level",
            field=models.DecimalField(
                decimal_places=2,
                default=5,
                max_digits=12,
                verbose_name="จุดสั่งซื้อ (Low Stock)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_qty",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="จำนวนคงเหลือ"
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="จำนวน"
            ),
        ),
    ]
