# Generated by Django 5.1.3 on 2026-05-24 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_alter_product_min_level_alter_product_stock_qty_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ชื่อหมวดหมู่ย่อย"
                    ),
                ),
            ],
            options={
                "verbose_name": "1.2 หมวดหมู่ย่อย",
                "verbose_name_plural": "1.2 จัดการหมวดหมู่ย่อย",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.category",
                verbose_name="หมวดหมู่สินค้า",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sub_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.subcategory",
                verbose_name="หมวดหมู่ย่อย",
            ),
        ),
    ]
