# Generated by Django 4.2.30 on 2026-09-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_subcategory_alter_product_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventorydoc",
            options={},
        ),
        migrations.AddField(
            model_name="inventorydoc",
            name="slip_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="inventory_receipts/%Y/%m/",
                verbose_name="รูปใบส่งของ/รับของ",
            ),
        ),
    ]
