# Generated by Django 4.2.30 on 2026-09-23 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_alter_inventorydoc_options_inventorydoc_slip_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventorydoc",
            options={
                "verbose_name": "3. เอกสารคลังสินค้า",
                "verbose_name_plural": "3. เอกสารคลังสินค้า (Docs)",
            },
        ),
    ]
