# Generated by Django 4.2.30 on 2026-09-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0017_alter_inventorydoc_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="physical_qty",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="ยอดจริงหน้าลาน (Physical)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_qty",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="ยอดพร้อมขาย (Available)",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("IN", "เข้า (รับเข้าคลัง)"),
                    ("OUT", "ออก (เบิก/ปรับปรุง)"),
                    ("RESERVE", "จอง (ตัดยอดพร้อมขาย)"),
                    ("DISPATCH", "ส่งมอบ (ตัดยอดหน้าลาน)"),
                ],
                max_length=15,
                verbose_name="ประเภท",
            ),
        ),
    ]
