# Generated by Django 5.2.9 on 2026-01-04 11:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hr", "0001_initial"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BOM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="ชื่อสูตร (เช่น สูตรมาตรฐาน)"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="หมายเหตุ")),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                        verbose_name="สินค้าสำเร็จรูป (FG)",
                    ),
                ),
            ],
            options={
                "verbose_name": "1. สูตรการผลิต (BOM)",
                "verbose_name_plural": "1. จัดการสูตรผลิต",
            },
        ),
        migrations.CreateModel(
            name="BOMItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        verbose_name="จำนวนที่ใช้ (ต่อ 1 หน่วยผลิต)",
                    ),
                ),
                (
                    "bom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="manufacturing.bom",
                    ),
                ),
                (
                    "raw_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_in_boms",
                        to="inventory.product",
                        verbose_name="วัตถุดิบ (Raw Mat)",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductionOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="เลขที่ใบสั่งผลิต"
                    ),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="จำนวนที่ผลิต")),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="วันที่เริ่ม"
                    ),
                ),
                (
                    "finish_date",
                    models.DateField(blank=True, null=True, verbose_name="วันที่เสร็จ"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "วางแผน"),
                            ("IN_PROGRESS", "กำลังผลิต"),
                            ("COMPLETED", "ผลิตเสร็จแล้ว (เข้าสต็อก)"),
                            ("CANCELLED", "ยกเลิก"),
                        ],
                        default="PLANNED",
                        max_length=20,
                        verbose_name="สถานะ",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="หมายเหตุ")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                        verbose_name="สินค้าที่จะผลิต",
                    ),
                ),
                (
                    "responsible_person",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.employee",
                        verbose_name="ผู้ควบคุมการผลิต",
                    ),
                ),
            ],
            options={
                "verbose_name": "2. ใบสั่งผลิต",
                "verbose_name_plural": "2. จัดการการผลิต",
            },
        ),
    ]
