# Generated by Django 5.1.3 on 2026-03-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionorder",
            name="is_materials_ordered",
            field=models.BooleanField(default=False, verbose_name="สั่งซื้อวัตถุดิบแล้ว"),
        ),
    ]
