# Generated by Django 5.1.3 on 2026-03-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0002_productionorder_is_materials_ordered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionorder",
            name="code",
            field=models.CharField(
                blank=True, max_length=20, unique=True, verbose_name="เลขที่ใบสั่งผลิต (JOB)"
            ),
        ),
        migrations.AlterField(
            model_name="productionorder",
            name="quantity",
            field=models.IntegerField(
                default=1, verbose_name="จำนวนที่ผลิต (ล็อกที่ 1 เสมอ)"
            ),
        ),
    ]
