# Generated by Django 5.1.3 on 2026-03-02 11:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0003_alter_productionorder_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ชื่อสาขา"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="productionorder",
            name="customer_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="ชื่อลูกค้า / สถานที่ส่ง"
            ),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="delivery_date",
            field=models.DateField(blank=True, null=True, verbose_name="กำหนดจัดส่งสินค้า"),
        ),
        migrations.AlterField(
            model_name="productionorder",
            name="finish_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="วันที่เสร็จ (เข้าคลัง)"
            ),
        ),
        migrations.AlterField(
            model_name="productionorder",
            name="start_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="วันที่เริ่มผลิต"
            ),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manufacturing.branch",
                verbose_name="สาขาที่ขาย",
            ),
        ),
        migrations.CreateModel(
            name="Salesperson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="ชื่อพนักงานขาย")),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salespersons",
                        to="manufacturing.branch",
                        verbose_name="สาขา",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="productionorder",
            name="salesperson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manufacturing.salesperson",
                verbose_name="พนักงานขาย",
            ),
        ),
    ]
