# Generated by Django 5.1.3 on 2026-03-02 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0004_branch_productionorder_customer_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="สถานะการจัดส่ง"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductionStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="สถานะการผลิตหน้างาน"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductionTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ชื่อทีมช่าง"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transporter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ทีมขนส่ง / บริษัทขนส่ง"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="productionorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNED", "วางแผน"),
                    ("IN_PROGRESS", "กำลังผลิต"),
                    ("COMPLETED", "ผลิตเสร็จแล้ว (เข้าสต็อก)"),
                    ("CANCELLED", "ยกเลิก"),
                ],
                default="PLANNED",
                max_length=20,
                verbose_name="สถานะระบบ",
            ),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="delivery_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manufacturing.deliverystatus",
                verbose_name="สถานะจัดส่ง",
            ),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="production_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manufacturing.productionstatus",
                verbose_name="สถานะหน้างาน",
            ),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="production_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manufacturing.productionteam",
                verbose_name="ทีมช่างผลิต",
            ),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="transporter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manufacturing.transporter",
                verbose_name="ทีมขนส่ง",
            ),
        ),
    ]
