# Generated by Django 5.1.3 on 2026-03-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "manufacturing",
            "0005_deliverystatus_productionstatus_productionteam_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="productionorder",
            name="is_closed",
            field=models.BooleanField(
                default=False, verbose_name="ปิดจ๊อบแล้ว (งานเสร็จสมบูรณ์)"
            ),
        ),
    ]
