# Generated by Django 5.1.3 on 2026-03-22 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_inventorydoc_po_reference_and_more"),
        ("manufacturing", "0006_productionorder_is_closed"),
        ("sales", "0012_invoice_check_bank_invoice_check_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionorder",
            name="blueprint_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="blueprints/%Y/%m/",
                verbose_name="ไฟล์แบบแปลน (PDF/รูปภาพ)",
            ),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="quotation_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="production_orders",
                to="sales.quotation",
                verbose_name="อ้างอิงใบเสนอราคา/มัดจำ",
            ),
        ),
        migrations.CreateModel(
            name="ProductionOrderMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="จำนวนที่ต้องใช้"
                    ),
                ),
                (
                    "is_additional",
                    models.BooleanField(
                        default=False, verbose_name="เป็นรายการสั่งเพิ่มพิเศษ (ไม่อยู่ใน BOM)"
                    ),
                ),
                (
                    "production_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="manufacturing.productionorder",
                    ),
                ),
                (
                    "raw_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                        verbose_name="วัตถุดิบ",
                    ),
                ),
            ],
            options={
                "verbose_name": "3. วัตถุดิบในใบสั่งผลิต",
                "verbose_name_plural": "3. จัดการวัตถุดิบในงานผลิต",
            },
        ),
    ]
