# Generated by Django 5.1.3 on 2026-03-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0007_productionorder_blueprint_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNED", "วางแผนผลิต"),
                    ("WAITING_MATERIALS", "เตรียมสั่งซื้อวัตถุดิบ"),
                    ("READY_TO_PRODUCE", "พร้อมสั่งผลิต"),
                    ("IN_PROGRESS", "อยู่ระหว่างผลิต"),
                    ("COMPLETED", "ผลิตเสร็จแล้ว (เข้าสต็อก)"),
                    ("CANCELLED", "ยกเลิก"),
                ],
                default="PLANNED",
                max_length=20,
                verbose_name="สถานะระบบ",
            ),
        ),
    ]
