# Generated by Django 5.1.3 on 2026-03-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0008_alter_productionorder_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNED", "รอตรวจสอบแบบแปลน"),
                    ("WAITING_MATERIALS", "รอสั่งซื้อวัตถุดิบ"),
                    ("WAITING_INVENTORY", "รอวัตถุดิบพร้อมผลิต"),
                    ("IN_PROGRESS", "งานอยู่ระหว่างผลิต"),
                    ("COMPLETED", "ผลิตเสร็จแล้ว (เข้าสต็อก)"),
                    ("CANCELLED", "ยกเลิก"),
                ],
                default="PLANNED",
                max_length=20,
                verbose_name="สถานะระบบ",
            ),
        ),
    ]
