# Generated by Django 5.1.3 on 2026-03-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0009_alter_productionorder_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productionorder",
            name="production_status",
        ),
        migrations.AddField(
            model_name="productionorder",
            name="completed_departments",
            field=models.ManyToManyField(
                blank=True,
                to="manufacturing.productionstatus",
                verbose_name="แผนกที่ดำเนินการเสร็จแล้ว",
            ),
        ),
        migrations.AlterField(
            model_name="productionstatus",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="สถานะการผลิตหน้างาน (แผนก)"
            ),
        ),
    ]
