# Generated by Django 5.1.3 on 2026-03-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0010_remove_productionorder_production_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productionstatus",
            options={"ordering": ["sequence", "id"]},
        ),
        migrations.AddField(
            model_name="productionstatus",
            name="sequence",
            field=models.IntegerField(default=99, verbose_name="ลำดับการแสดงผล"),
        ),
    ]
