# Generated by Django 5.1.3 on 2026-04-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0011_alter_productionstatus_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionorder",
            name="cohort_week",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="สัปดาห์คิวผลิต (Cohort)"
            ),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="deadline_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="เส้นตายจัดส่ง (SLA)"
            ),
        ),
    ]
