# Generated by Django 5.1.3 on 2026-04-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0013_mfgbranch_alter_branch_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mfgbranch",
            name="weekly_quota",
            field=models.IntegerField(
                default=10, verbose_name="โควตาการผลิต (หลัง/สัปดาห์)"
            ),
        ),
    ]
