# Generated by Django 5.1.3 on 2026-04-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0014_mfgbranch_weekly_quota"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionorder",
            name="auto_calculated_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="วันที่ระบบคำนวณ (Safe Date)"
            ),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="date_approval_status",
            field=models.CharField(
                choices=[
                    ("NOT_REQUIRED", "ไม่ต้องอนุมัติ"),
                    ("PENDING", "รออนุมัติวัน"),
                    ("APPROVED", "อนุมัติวันแล้ว"),
                    ("REJECTED", "ไม่อนุมัติ (ยึดตามระบบ)"),
                ],
                default="NOT_REQUIRED",
                max_length=20,
                verbose_name="สถานะการอนุมัติวัน",
            ),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="requested_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="วันที่เซลส์ขอ (Requested Date)"
            ),
        ),
    ]
