# Generated by Django 5.1.3 on 2026-04-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0015_productionorder_auto_calculated_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW_JOB", "รอเปิดการผลิต (New JOBs)"),
                    ("PLANNED", "รอคิวเตรียมของ / ตรวจแบบ"),
                    ("WAITING_MATERIALS", "รอสั่งซื้อวัตถุดิบ"),
                    ("WAITING_INVENTORY", "รอวัตถุดิบพร้อมผลิต"),
                    ("IN_PROGRESS", "กำลังผลิต"),
                    ("COMPLETED", "พร้อมจัดส่ง / เสร็จแล้ว (เข้าสต็อก)"),
                    ("CANCELLED", "ยกเลิก"),
                ],
                default="NEW_JOB",
                max_length=20,
                verbose_name="สถานะระบบ",
            ),
        ),
    ]
