# Generated by Django 5.1.3 on 2026-04-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0016_alter_productionorder_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliverystatus",
            options={
                "verbose_name": "สถานะการจัดส่ง",
                "verbose_name_plural": "สถานะการจัดส่ง",
            },
        ),
        migrations.AlterModelOptions(
            name="productionstatus",
            options={
                "ordering": ["sequence", "id"],
                "verbose_name": "สถานะการผลิต",
                "verbose_name_plural": "สถานะการผลิต",
            },
        ),
        migrations.AlterModelOptions(
            name="productionteam",
            options={"verbose_name": "ทีมช่างผลิต", "verbose_name_plural": "ทีมช่างผลิต"},
        ),
        migrations.AlterModelOptions(
            name="transporter",
            options={"verbose_name": "ทีมขนส่ง", "verbose_name_plural": "ทีมขนส่ง"},
        ),
        migrations.AddField(
            model_name="productionorder",
            name="is_qc_passed",
            field=models.BooleanField(default=False, verbose_name="ผ่าน QC แล้ว"),
        ),
    ]
