# Generated by Django 5.1.3 on 2026-04-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0017_alter_deliverystatus_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW_JOB", "1. รอจ่ายงาน (New JOB)"),
                    ("PLANNED", "2. ตรวจแบบแปลน / ดึงสูตร"),
                    ("WAITING_MATERIALS", "3. รอสั่งซื้อวัตถุดิบ"),
                    ("WAITING_INVENTORY", "4. รอเบิกวัตถุดิบ"),
                    ("IN_PROGRESS", "5. กำลังผลิต"),
                    ("COMPLETED", "6. พร้อมจัดส่ง / เสร็จแล้ว (เข้าสต็อก)"),
                    ("CANCELLED", "ยกเลิก"),
                ],
                default="NEW_JOB",
                max_length=20,
                verbose_name="สถานะระบบ",
            ),
        ),
    ]
