# Generated by Django 5.1.3 on 2026-04-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0018_alter_productionorder_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionorder",
            name="qc_aircon",
            field=models.BooleanField(default=False, verbose_name="6. งานเช็คระบบแอร์"),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="qc_electrical",
            field=models.BooleanField(default=False, verbose_name="4. งานเช็คระบบไฟฟ้า"),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="qc_external",
            field=models.BooleanField(default=False, verbose_name="3. งานตรวจภายนอก"),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="qc_internal",
            field=models.BooleanField(default=False, verbose_name="2. งานตรวจภายใน"),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="qc_paint",
            field=models.BooleanField(default=False, verbose_name="1. งานเก็บสี"),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="qc_plumbing",
            field=models.BooleanField(
                default=False, verbose_name="5. งานเช็คระบบน้ำประปา"
            ),
        ),
    ]
