# Generated by Django 5.1.3 on 2026-04-19 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0011_department_parent"),
        ("manufacturing", "0019_productionorder_qc_aircon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionorder",
            name="rework_count",
            field=models.IntegerField(
                default=0, verbose_name="จำนวนครั้งที่ถูกตีกลับ (Rework)"
            ),
        ),
        migrations.AlterField(
            model_name="productionorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW_JOB", "1. รอจ่ายงาน (New JOB)"),
                    ("PLANNED", "2. ตรวจแบบแปลน / ดึงสูตร"),
                    ("WAITING_MATERIALS", "3. รอสั่งซื้อวัตถุดิบ"),
                    ("WAITING_INVENTORY", "4. รอเบิกวัตถุดิบ"),
                    ("IN_PROGRESS", "5. กำลังผลิต"),
                    ("WAITING_QC", "รอตรวจสอบคุณภาพ (QC)"),
                    ("REWORK", "รอแก้ไขงาน (Rework)"),
                    ("COMPLETED", "6. พร้อมจัดส่ง / เสร็จแล้ว (เข้าสต็อก)"),
                    ("CANCELLED", "ยกเลิก"),
                ],
                default="NEW_JOB",
                max_length=20,
                verbose_name="สถานะระบบ",
            ),
        ),
        migrations.CreateModel(
            name="QCInspectionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "round_number",
                    models.IntegerField(default=1, verbose_name="ตรวจครั้งที่"),
                ),
                (
                    "inspected_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="เวลาที่ตรวจ"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PASSED", "ผ่าน"), ("FAILED", "ไม่ผ่าน/ตีกลับ")],
                        default="FAILED",
                        max_length=20,
                        verbose_name="ผลการตรวจ",
                    ),
                ),
                (
                    "comments",
                    models.TextField(blank=True, verbose_name="คอมเมนต์/จุดที่ต้องแก้ไข"),
                ),
                (
                    "defect_image_1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="qc_defects/%Y/%m/",
                        verbose_name="รูปภาพประกอบ 1",
                    ),
                ),
                (
                    "defect_image_2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="qc_defects/%Y/%m/",
                        verbose_name="รูปภาพประกอบ 2",
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.employee",
                        verbose_name="ผู้ตรวจสอบ (QC)",
                    ),
                ),
                (
                    "production_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qc_logs",
                        to="manufacturing.productionorder",
                        verbose_name="ใบสั่งผลิต",
                    ),
                ),
            ],
        ),
    ]
