# Generated by Django 5.1.3 on 2026-05-02 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0012_employee_production_team"),
        ("manufacturing", "0020_productionorder_rework_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionorder",
            name="blueprint_approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="เวลาที่อนุมัติแบบแปลน"
            ),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="blueprint_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_blueprints",
                to="hr.employee",
                verbose_name="ผู้อนุมัติแบบแปลน",
            ),
        ),
        migrations.AlterField(
            model_name="productionorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW_JOB", "1. รอจ่ายงาน (New JOB)"),
                    ("WAITING_BLUEPRINT", "รอตรวจสอบแบบแปลน"),
                    ("PLANNED", "2. ตรวจแบบแปลน / ดึงสูตร"),
                    ("WAITING_MATERIALS", "3. รอสั่งซื้อวัตถุดิบ"),
                    ("WAITING_INVENTORY", "4. รอเบิกวัตถุดิบ"),
                    ("IN_PROGRESS", "5. กำลังผลิต"),
                    ("WAITING_QC", "รอตรวจสอบคุณภาพ (QC)"),
                    ("REWORK", "รอแก้ไขงาน (Rework)"),
                    ("COMPLETED", "6. พร้อมจัดส่ง / เสร็จแล้ว (เข้าสต็อก)"),
                    ("CANCELLED", "ยกเลิก"),
                ],
                default="NEW_JOB",
                max_length=20,
                verbose_name="สถานะระบบ",
            ),
        ),
        migrations.CreateModel(
            name="BlueprintClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="เลขที่ใบตั้งเบิก"
                    ),
                ),
                (
                    "total_jobs",
                    models.IntegerField(default=0, verbose_name="จำนวนงานที่เบิก"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="ยอดเงินรวม",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "รออนุมัติจ่าย"),
                            ("PAID", "จ่ายเงินแล้ว"),
                            ("REJECTED", "ไม่อนุมัติ"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="สถานะ",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่ตั้งเบิก"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="วันที่จ่ายเงิน"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.employee",
                        verbose_name="พนักงานผู้ขอเบิก",
                    ),
                ),
            ],
            options={
                "verbose_name": "ใบตั้งเบิกผลงานตรวจแบบ",
                "verbose_name_plural": "ใบตั้งเบิกผลงานตรวจแบบ",
            },
        ),
        migrations.AddField(
            model_name="productionorder",
            name="blueprint_claim",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="production_orders",
                to="manufacturing.blueprintclaim",
                verbose_name="ใบตั้งเบิกผลงาน",
            ),
        ),
        migrations.CreateModel(
            name="BlueprintLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(max_length=255, verbose_name="รายละเอียดการอัปเดต"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="เวลาที่ดำเนินการ"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.employee",
                        verbose_name="ผู้ดำเนินการ",
                    ),
                ),
                (
                    "production_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blueprint_logs",
                        to="manufacturing.productionorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
