# Generated by Django 5.1.3 on 2026-05-02 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0013_salesgroup_flat_rate_amount"),
        ("manufacturing", "0021_productionorder_blueprint_approved_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlueprintClaimSplit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_name",
                    models.CharField(max_length=50, verbose_name="ตำแหน่งในทีม (ตอนเบิก)"),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="เปอร์เซ็นต์ที่ได้"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="ยอดเงินสุทธิ"
                    ),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="splits",
                        to="manufacturing.blueprintclaim",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.employee",
                        verbose_name="ผู้รับเงินส่วนแบ่ง",
                    ),
                ),
            ],
            options={
                "verbose_name": "ส่วนแบ่งใบเบิก",
                "verbose_name_plural": "ส่วนแบ่งใบเบิก",
            },
        ),
    ]
