# Generated by Django 5.1.3 on 2026-05-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0022_blueprintclaimsplit"),
    ]

    operations = [
        migrations.AddField(
            model_name="transporter",
            name="delivery_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="ค่าตอบแทนเหมาจ่าย (ต่อเที่ยว)",
            ),
        ),
        migrations.AddField(
            model_name="transporter",
            name="driver_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="ชื่อคนขับหลัก"
            ),
        ),
        migrations.AddField(
            model_name="transporter",
            name="vehicle_plate",
            field=models.CharField(blank=True, max_length=50, verbose_name="ทะเบียนรถ"),
        ),
    ]
