# Generated by Django 5.1.3 on 2026-05-03 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "manufacturing",
            "0023_transporter_delivery_fee_transporter_driver_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="productionorder",
            name="is_onsite",
            field=models.BooleanField(
                default=False, verbose_name="งานประกอบหน้างาน (On-site)"
            ),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="proof_of_delivery",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="delivery_proofs/%Y/%m/",
                verbose_name="รูปถ่ายใบส่งมอบสินค้า",
            ),
        ),
        migrations.CreateModel(
            name="LogisticsClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="เลขที่ใบเบิก"
                    ),
                ),
                (
                    "total_jobs",
                    models.IntegerField(default=0, verbose_name="จำนวนงานที่เบิก"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="ยอดเงินรวม",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "รออนุมัติจ่าย"),
                            ("PAID", "จ่ายเงินแล้ว"),
                            ("REJECTED", "ไม่อนุมัติ"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="สถานะ",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่ตั้งเบิก"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="วันที่จ่ายเงิน"
                    ),
                ),
                (
                    "transporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manufacturing.transporter",
                        verbose_name="ทีมขนส่ง",
                    ),
                ),
            ],
            options={
                "verbose_name": "ใบตั้งเบิกค่าขนส่ง",
                "verbose_name_plural": "ใบตั้งเบิกค่าขนส่ง",
            },
        ),
        migrations.AddField(
            model_name="productionorder",
            name="logistics_claim",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="production_orders",
                to="manufacturing.logisticsclaim",
                verbose_name="ใบตั้งเบิกค่ารถขนส่ง",
            ),
        ),
    ]
