# Generated by Django 5.1.3 on 2026-05-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0024_productionorder_is_onsite_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionorder",
            name="delivery_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="ค่าจ้างขนส่ง (สำหรับงานนี้)",
            ),
        ),
        migrations.AddField(
            model_name="transporter",
            name="address",
            field=models.TextField(blank=True, verbose_name="ที่อยู่บริษัท / คนขับ"),
        ),
        migrations.AddField(
            model_name="transporter",
            name="bank_account",
            field=models.CharField(
                blank=True,
                max_length=200,
                verbose_name="เลขที่บัญชีธนาคาร (ระบุชื่อธนาคารด้วย)",
            ),
        ),
        migrations.AddField(
            model_name="transporter",
            name="id_card_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="transporter_docs/",
                verbose_name="เอกสารใบขับขี่ / บัตรประชาชน",
            ),
        ),
        migrations.AlterField(
            model_name="transporter",
            name="delivery_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="ค่าตอบแทนพื้นฐาน",
            ),
        ),
    ]
