# Generated by Django 5.1.3 on 2026-05-31 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "manufacturing",
            "0025_productionorder_delivery_fee_transporter_address_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bom",
            name="labor_cost",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="ค่าแรงประกอบ"
            ),
        ),
    ]
