# Generated by Django 4.2.30 on 2026-09-20 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0014_position_approval_authority_position_description"),
        ("manufacturing", "0026_bom_labor_cost"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobOtherExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="เลขที่ใบเบิก"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=255, verbose_name="รายการที่เบิก (เช่น ซื้อน็อต, ค่าน้ำมัน)"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="ยอดเบิก",
                    ),
                ),
                (
                    "receipt_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="expense_receipts/%Y/%m/",
                        verbose_name="รูปบิลใบเสร็จ/สลิป",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "รอจ่ายเงิน (Pending)"),
                            ("PAID", "จ่ายเงินแล้ว (Paid)"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="สถานะการจ่ายเงิน",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่ตั้งเบิก"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="วันที่จ่ายเงิน"
                    ),
                ),
                (
                    "production_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="other_expenses",
                        to="manufacturing.productionorder",
                        verbose_name="อ้างอิงเลขที่ JOB",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.employee",
                        verbose_name="พนักงานผู้ขอเบิก",
                    ),
                ),
            ],
            options={
                "verbose_name": "ใบเบิกค่าใช้จ่ายอื่นๆ",
                "verbose_name_plural": "ใบเบิกค่าใช้จ่ายอื่นๆ",
            },
        ),
        migrations.CreateModel(
            name="JobLaborClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="เลขที่ใบเบิก"
                    ),
                ),
                (
                    "contractor_name",
                    models.CharField(
                        max_length=150, verbose_name="ชื่อผู้รับเหมา / หัวหน้าช่าง"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="ยอดเบิกค่าแรง",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "รอจ่ายเงิน (Pending)"),
                            ("PAID", "จ่ายเงินแล้ว (Paid)"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="สถานะการจ่ายเงิน",
                    ),
                ),
                (
                    "slip_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="labor_slips/%Y/%m/",
                        verbose_name="สลิปหลักฐานการโอน",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่ตั้งเบิก"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="วันที่จ่ายเงิน"
                    ),
                ),
                (
                    "production_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labor_claims",
                        to="manufacturing.productionorder",
                        verbose_name="อ้างอิงเลขที่ JOB",
                    ),
                ),
            ],
            options={
                "verbose_name": "ใบเบิกค่าแรงเหมา",
                "verbose_name_plural": "ใบเบิกค่าแรงเหมา",
            },
        ),
        migrations.CreateModel(
            name="JobAirconClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="เลขที่ใบเบิก"
                    ),
                ),
                (
                    "technician_name",
                    models.CharField(max_length=150, verbose_name="ชื่อช่างแอร์ / ร้านแอร์"),
                ),
                (
                    "description",
                    models.TextField(verbose_name="รายละเอียด (เช่น แอร์ 12000 BTU)"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="ยอดเบิกค่าแอร์",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "รอจ่ายเงิน (Pending)"),
                            ("PAID", "จ่ายเงินแล้ว (Paid)"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="สถานะการจ่ายเงิน",
                    ),
                ),
                (
                    "slip_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="aircon_slips/%Y/%m/",
                        verbose_name="สลิปหลักฐานการโอน",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่ตั้งเบิก"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="วันที่จ่ายเงิน"
                    ),
                ),
                (
                    "production_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aircon_claims",
                        to="manufacturing.productionorder",
                        verbose_name="อ้างอิงเลขที่ JOB",
                    ),
                ),
            ],
            options={
                "verbose_name": "ใบเบิกค่าติดตั้งแอร์",
                "verbose_name_plural": "ใบเบิกค่าติดตั้งแอร์",
            },
        ),
    ]
