# Generated by Django 4.2.30 on 2026-09-21 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0014_position_approval_authority_position_description"),
        ("manufacturing", "0027_jobotherexpense_joblaborclaim_jobairconclaim"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobairconclaim",
            name="requester",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hr.employee",
                verbose_name="พนักงานผู้หยอดกระปุก",
            ),
        ),
        migrations.AddField(
            model_name="joblaborclaim",
            name="requester",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hr.employee",
                verbose_name="พนักงานผู้หยอดกระปุก",
            ),
        ),
        migrations.AlterField(
            model_name="jobairconclaim",
            name="slip_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="aircon_slips/%Y/%m/",
                verbose_name="หลักฐานการติดตั้ง",
            ),
        ),
        migrations.AlterField(
            model_name="jobairconclaim",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNCLAIMED", "รอตั้งเบิก (ในตะกร้า)"),
                    ("PENDING", "รอจ่ายเงิน (Pending)"),
                    ("PAID", "จ่ายเงินแล้ว (Paid)"),
                ],
                default="UNCLAIMED",
                max_length=20,
                verbose_name="สถานะการจ่ายเงิน",
            ),
        ),
        migrations.AlterField(
            model_name="joblaborclaim",
            name="slip_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="labor_slips/%Y/%m/",
                verbose_name="หลักฐานหน้างาน",
            ),
        ),
        migrations.AlterField(
            model_name="joblaborclaim",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNCLAIMED", "รอตั้งเบิก (ในตะกร้า)"),
                    ("PENDING", "รอจ่ายเงิน (Pending)"),
                    ("PAID", "จ่ายเงินแล้ว (Paid)"),
                ],
                default="UNCLAIMED",
                max_length=20,
                verbose_name="สถานะการจ่ายเงิน",
            ),
        ),
        migrations.AlterField(
            model_name="jobotherexpense",
            name="receipt_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="expense_receipts/%Y/%m/",
                verbose_name="รูปบิลใบเสร็จ",
            ),
        ),
        migrations.AlterField(
            model_name="jobotherexpense",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNCLAIMED", "รอตั้งเบิก (ในตะกร้า)"),
                    ("PENDING", "รอจ่ายเงิน (Pending)"),
                    ("PAID", "จ่ายเงินแล้ว (Paid)"),
                ],
                default="UNCLAIMED",
                max_length=20,
                verbose_name="สถานะการจ่ายเงิน",
            ),
        ),
        migrations.CreateModel(
            name="MasterExpenseClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="เลขที่ใบคุม"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="ยอดรวมสุทธิ",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        choices=[
                            ("KBANK", "กสิกรไทย (KBANK)"),
                            ("SCB", "ไทยพาณิชย์ (SCB)"),
                            ("BBL", "กรุงเทพ (BBL)"),
                            ("KTB", "กรุงไทย (KTB)"),
                            ("BAY", "กรุงศรีอยุธยา (BAY)"),
                            ("TTB", "ทหารไทยธนชาต (TTB)"),
                            ("GSB", "ออมสิน (GSB)"),
                            ("BAAC", "ธ.ก.ส. (BAAC)"),
                            ("PROMPTPAY", "พร้อมเพย์ (PromptPay)"),
                            ("OTHER", "อื่นๆ"),
                        ],
                        max_length=20,
                        verbose_name="ธนาคาร",
                    ),
                ),
                (
                    "bank_account_number",
                    models.CharField(max_length=50, verbose_name="เลขที่บัญชี / พร้อมเพย์"),
                ),
                (
                    "bank_account_name",
                    models.CharField(max_length=150, verbose_name="ชื่อบัญชี"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "รอโอนเงิน (Pending)"),
                            ("PAID", "โอนเงินแล้ว (Paid)"),
                            ("REJECTED", "ไม่อนุมัติ (Rejected)"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="สถานะ",
                    ),
                ),
                (
                    "transfer_slip",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="master_claims/%Y/%m/",
                        verbose_name="สลิปโอนเงินจากบัญชี",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่สร้างใบคุม"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="วันที่ทำจ่าย"
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.employee",
                        verbose_name="พนักงานผู้ขอเบิก",
                    ),
                ),
            ],
            options={
                "verbose_name": "ใบคุมเบิกรวม (JOB Expenses)",
                "verbose_name_plural": "ใบคุมเบิกรวม (JOB Expenses)",
            },
        ),
        migrations.AddField(
            model_name="jobairconclaim",
            name="master_claim",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aircon_items",
                to="manufacturing.masterexpenseclaim",
                verbose_name="ใบคุมรวม",
            ),
        ),
        migrations.AddField(
            model_name="joblaborclaim",
            name="master_claim",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="labor_items",
                to="manufacturing.masterexpenseclaim",
                verbose_name="ใบคุมรวม",
            ),
        ),
        migrations.AddField(
            model_name="jobotherexpense",
            name="master_claim",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="other_items",
                to="manufacturing.masterexpenseclaim",
                verbose_name="ใบคุมรวม",
            ),
        ),
    ]
