# Generated by Django 4.2.30 on 2026-09-25 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0017_alter_inventorydoc_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "manufacturing",
            "0028_jobairconclaim_requester_joblaborclaim_requester_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="QCReceiptDoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_no",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="เลขที่ใบรับสินค้า (FG)",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="จำนวนรับเข้า"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="เวลาที่รับเข้า"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ทำรายการ (QC)",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                        verbose_name="สินค้าสำเร็จรูป",
                    ),
                ),
                (
                    "production_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qc_receipt",
                        to="manufacturing.productionorder",
                        verbose_name="อ้างอิงใบสั่งผลิต",
                    ),
                ),
            ],
            options={
                "verbose_name": "ใบรับสินค้าสำเร็จรูป (QC)",
                "verbose_name_plural": "ใบรับสินค้าสำเร็จรูป (QC)",
            },
        ),
    ]
