# Generated by Django 4.2.30 on 2026-09-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0029_qcreceiptdoc"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionorder",
            name="ppo_ref",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="เลขที่ใบ PPO ที่ผูกไว้"
            ),
        ),
    ]
