# Generated by Django 5.2.9 on 2026-01-04 11:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hr", "0001_initial"),
        ("inventory", "0001_initial"),
        ("master_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="เลขที่ใบสั่งซื้อ (PO)"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="วันที่สั่งซื้อ"
                    ),
                ),
                (
                    "expected_date",
                    models.DateField(blank=True, null=True, verbose_name="กำหนดรับของ"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="ยอดรวม",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "ร่าง (รออนุมัติ)"),
                            ("ORDERED", "สั่งซื้อแล้ว (รอของ)"),
                            ("RECEIVED", "ได้รับสินค้าแล้ว (เข้าสต็อก)"),
                            ("CANCELLED", "ยกเลิก"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="สถานะ",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="หมายเหตุ")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.employee",
                        verbose_name="ผู้จัดซื้อ",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="master_data.supplier",
                        verbose_name="ผู้ขาย (Supplier)",
                    ),
                ),
            ],
            options={
                "verbose_name": "1. ใบสั่งซื้อ (PO)",
                "verbose_name_plural": "1. จัดการใบสั่งซื้อ",
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="จำนวนที่สั่ง")),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="ต้นทุนต่อหน่วย"
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="รวมเป็นเงิน"
                    ),
                ),
                (
                    "po",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchasing.purchaseorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.product",
                        verbose_name="สินค้า",
                    ),
                ),
            ],
        ),
    ]
