# Generated by Django 5.1.3 on 2026-03-01 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_finishedgood_rawmaterial"),
        ("manufacturing", "0002_productionorder_is_materials_ordered"),
        ("purchasing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="delivery_status",
            field=models.CharField(
                choices=[("PENDING", "รอดำเนินการจัดส่ง"), ("SHIPPED", "ร้านค้าส่งของแล้ว")],
                default="PENDING",
                max_length=20,
                verbose_name="สถานะจัดส่ง",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "รอชำระเงิน"),
                    ("DEPOSIT", "จ่ายมัดจำแล้ว"),
                    ("PAID", "ชำระครบแล้ว"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="สถานะชำระเงิน",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="production_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_pos",
                to="manufacturing.productionorder",
                verbose_name="อ้างอิงใบสั่งผลิต",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="receipt_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "รอรับเข้าคลัง"),
                    ("PARTIAL", "รับของบางส่วน"),
                    ("COMPLETED", "รับของครบถ้วน"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="สถานะรับของเข้าคลัง",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="received_qty",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="จำนวนที่รับเข้าคลังแล้ว",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "ร่าง (รออนุมัติ)"),
                    ("APPROVED", "อนุมัติแล้ว (ดำเนินการสั่งซื้อ)"),
                    ("CANCELLED", "ยกเลิก"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="สถานะเอกสาร",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.product",
                verbose_name="สินค้า/วัตถุดิบ",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=10, verbose_name="จำนวนที่สั่ง"
            ),
        ),
    ]
