# Generated by Django 5.1.3 on 2026-03-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0002_purchaseorder_delivery_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="ppo_ref",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="อ้างอิงใบเตรียมการสั่งซื้อ (PPO)",
            ),
        ),
    ]
