# Generated by Django 5.1.3 on 2026-03-02 07:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0003_purchaseorder_ppo_ref"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrderPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="วันที่ชำระเงิน"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="ยอดชำระ"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        default="โอนเงิน", max_length=50, verbose_name="ช่องทางการชำระ"
                    ),
                ),
                (
                    "reference_no",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="เลขอ้างอิง / สลิป"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="หมายเหตุ")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "po",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="purchasing.purchaseorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "ประวัติการชำระเงิน PO",
                "verbose_name_plural": "ประวัติการชำระเงิน PO",
            },
        ),
    ]
