# Generated by Django 5.1.3 on 2026-03-02 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0007_alter_attendance_options_alter_commissionlog_options_and_more"),
        ("manufacturing", "0003_alter_productionorder_code_and_more"),
        ("purchasing", "0004_purchaseorderpayment"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchasePreparation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="เลขที่ใบเตรียมสั่งซื้อ (PPO)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.employee",
                        verbose_name="ผู้จัดทำ",
                    ),
                ),
                (
                    "production_orders",
                    models.ManyToManyField(
                        related_name="ppos",
                        to="manufacturing.productionorder",
                        verbose_name="อ้างอิงใบสั่งผลิต (JOB)",
                    ),
                ),
            ],
            options={
                "verbose_name": "ใบเตรียมสั่งซื้อ (PPO)",
                "verbose_name_plural": "ใบเตรียมสั่งซื้อ (PPO)",
            },
        ),
    ]
