# Generated by Django 5.1.3 on 2026-03-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0005_purchasepreparation"),
    ]

    operations = [
        migrations.CreateModel(
            name="OverseasPO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(max_length=200, verbose_name="ชื่อร้านค้า (Supplier)"),
                ),
                ("pi_number", models.CharField(max_length=50, verbose_name="เลขที่ PI")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="ยอดสั่งซื้อรวม",
                    ),
                ),
                (
                    "is_fully_paid",
                    models.BooleanField(default=False, verbose_name="ชำระครบแล้ว"),
                ),
                (
                    "deposit_date",
                    models.DateField(blank=True, null=True, verbose_name="วันที่ชำระมัดจำ"),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="ยอดมัดจำ",
                    ),
                ),
                (
                    "balance_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="วันที่ชำระส่วนที่เหลือ"
                    ),
                ),
                (
                    "balance_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="ยอดส่วนที่เหลือ",
                    ),
                ),
                (
                    "doc_fe",
                    models.BooleanField(default=False, verbose_name="ได้รับเอกสาร FE"),
                ),
                (
                    "doc_bl",
                    models.BooleanField(default=False, verbose_name="ได้รับเอกสาร BL"),
                ),
                (
                    "doc_pl",
                    models.BooleanField(default=False, verbose_name="ได้รับเอกสาร PL"),
                ),
                (
                    "doc_ci",
                    models.BooleanField(default=False, verbose_name="ได้รับเอกสาร CI"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "ใบสั่งซื้อต่างประเทศ",
                "verbose_name_plural": "ใบสั่งซื้อต่างประเทศ",
            },
        ),
    ]
