# Generated by Django 5.1.3 on 2026-04-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0006_overseaspo"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderpayment",
            name="slip_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="po_payment_slips/%Y/%m/",
                verbose_name="สลิปโอนเงิน",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderpayment",
            name="payment_method",
            field=models.CharField(
                default="โอนเงินผ่านธนาคาร", max_length=50, verbose_name="ช่องทางการชำระ"
            ),
        ),
    ]
