# Generated by Django 5.1.3 on 2026-04-16 03:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0007_purchaseorderpayment_slip_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OverseasSupplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="ชื่อร้านค้า (ต่างประเทศ)"
                    ),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=100, verbose_name="ประเทศ"),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ชื่อผู้ติดต่อ"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="เบอร์โทร/WeChat/WhatsApp",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="อีเมล"),
                ),
                ("note", models.TextField(blank=True, verbose_name="หมายเหตุ")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "2. ร้านค้าต่างประเทศ",
                "verbose_name_plural": "2. ฐานข้อมูลร้านค้าต่างประเทศ",
            },
        ),
        migrations.AlterModelOptions(
            name="overseaspo",
            options={
                "verbose_name": "3. ใบสั่งซื้อต่างประเทศ",
                "verbose_name_plural": "3. ติดตามสินค้านำเข้า",
            },
        ),
        migrations.RemoveField(
            model_name="overseaspo",
            name="is_fully_paid",
        ),
        migrations.AddField(
            model_name="overseaspo",
            name="doc_customs",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="overseas_docs/customs/%Y/%m/",
                verbose_name="ใบขนสินค้าขาเข้า",
            ),
        ),
        migrations.AddField(
            model_name="overseaspo",
            name="doc_pi",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="overseas_docs/pi/%Y/%m/",
                verbose_name="เอกสาร PI",
            ),
        ),
        migrations.AddField(
            model_name="overseaspo",
            name="eta_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="วันที่คาดว่าจะได้รับสินค้า"
            ),
        ),
        migrations.AddField(
            model_name="overseaspo",
            name="is_balance_approved",
            field=models.BooleanField(
                default=False, verbose_name="บัญชีอนุมัติจ่ายแล้ว (ส่วนที่เหลือ)"
            ),
        ),
        migrations.AddField(
            model_name="overseaspo",
            name="is_balance_requested",
            field=models.BooleanField(
                default=False, verbose_name="ส่งเรื่องเบิกบัญชีแล้ว (ส่วนที่เหลือ)"
            ),
        ),
        migrations.AddField(
            model_name="overseaspo",
            name="is_deposit_approved",
            field=models.BooleanField(
                default=False, verbose_name="บัญชีอนุมัติจ่ายแล้ว (มัดจำ)"
            ),
        ),
        migrations.AddField(
            model_name="overseaspo",
            name="is_deposit_requested",
            field=models.BooleanField(
                default=False, verbose_name="ส่งเรื่องเบิกบัญชีแล้ว (มัดจำ)"
            ),
        ),
        migrations.AddField(
            model_name="overseaspo",
            name="item_description",
            field=models.TextField(blank=True, verbose_name="รายการสินค้าที่สั่ง"),
        ),
        migrations.AddField(
            model_name="overseaspo",
            name="po_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="วันที่เปิดใบสั่งซื้อ"
            ),
        ),
        migrations.AddField(
            model_name="overseaspo",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "รอชำระเงิน"),
                    ("DEPOSITED", "มัดจำแล้ว"),
                    ("FULLY_PAID", "ชำระครบแล้ว"),
                    ("COMPLETED", "รับสินค้าแล้ว (ปิดบิล)"),
                    ("CANCELLED", "ยกเลิก"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="สถานะออเดอร์",
            ),
        ),
        migrations.AlterField(
            model_name="overseaspo",
            name="doc_bl",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="overseas_docs/bl/%Y/%m/",
                verbose_name="เอกสาร BL",
            ),
        ),
        migrations.AlterField(
            model_name="overseaspo",
            name="doc_ci",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="overseas_docs/ci/%Y/%m/",
                verbose_name="เอกสาร CI",
            ),
        ),
        migrations.AlterField(
            model_name="overseaspo",
            name="doc_fe",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="overseas_docs/fe/%Y/%m/",
                verbose_name="เอกสาร FE",
            ),
        ),
        migrations.AlterField(
            model_name="overseaspo",
            name="doc_pl",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="overseas_docs/pl/%Y/%m/",
                verbose_name="เอกสาร PL",
            ),
        ),
        migrations.AlterField(
            model_name="overseaspo",
            name="supplier_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="ชื่อร้านค้า (ข้อมูลเดิม)"
            ),
        ),
        migrations.AddField(
            model_name="overseaspo",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="purchasing.overseassupplier",
                verbose_name="ร้านค้าต่างประเทศ",
            ),
        ),
    ]
