# Generated by Django 5.1.3 on 2026-04-16 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0008_overseassupplier_alter_overseaspo_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="overseaspo",
            name="doc_bl",
        ),
        migrations.RemoveField(
            model_name="overseaspo",
            name="doc_ci",
        ),
        migrations.RemoveField(
            model_name="overseaspo",
            name="doc_customs",
        ),
        migrations.RemoveField(
            model_name="overseaspo",
            name="doc_fe",
        ),
        migrations.RemoveField(
            model_name="overseaspo",
            name="doc_pi",
        ),
        migrations.RemoveField(
            model_name="overseaspo",
            name="doc_pl",
        ),
        migrations.CreateModel(
            name="OverseasDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("PI", "Proforma Invoice (PI)"),
                            ("FE", "ใบเสร็จโอนเงิน (FE)"),
                            ("BL", "Bill of Lading (BL)"),
                            ("PL", "Packing List (PL)"),
                            ("CI", "Commercial Invoice (CI)"),
                            ("CUSTOMS", "ใบขนสินค้าขาเข้า"),
                        ],
                        max_length=20,
                        verbose_name="ประเภทเอกสาร",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="overseas_docs/%Y/%m/", verbose_name="ไฟล์เอกสาร"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="อัปโหลดเมื่อ"),
                ),
                (
                    "po",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="purchasing.overseaspo",
                        verbose_name="ใบสั่งซื้อที่เกี่ยวข้อง",
                    ),
                ),
            ],
            options={
                "verbose_name": "ไฟล์เอกสารนำเข้า",
                "verbose_name_plural": "อัลบั้มเอกสารนำเข้า",
            },
        ),
    ]
