# Generated by Django 5.1.3 on 2026-04-16 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "purchasing",
            "0009_remove_overseaspo_doc_bl_remove_overseaspo_doc_ci_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="overseaspo",
            name="item_description",
            field=models.TextField(blank=True, verbose_name="รายการสินค้าที่สั่ง (Note)"),
        ),
        migrations.AlterField(
            model_name="overseaspo",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="ยอดสั่งซื้อรวม (THB)",
            ),
        ),
        migrations.CreateModel(
            name="OverseasPOItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="overseas_items/%Y/%m/",
                        verbose_name="รูปภาพสินค้า",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="รายละเอียดสินค้า"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=1, max_digits=10, verbose_name="จำนวน"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="ราคาต่อหน่วย",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="ราคารวม",
                    ),
                ),
                (
                    "po",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overseas_items",
                        to="purchasing.overseaspo",
                        verbose_name="ใบสั่งซื้อ",
                    ),
                ),
            ],
            options={
                "verbose_name": "รายการสินค้าต่างประเทศ",
                "verbose_name_plural": "รายการสินค้าต่างประเทศ",
            },
        ),
    ]
