# Generated by Django 5.1.3 on 2026-04-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0010_alter_overseaspo_item_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="overseaspo",
            name="po_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="เลขที่เอกสารเรา (PQ)",
            ),
        ),
        migrations.AddField(
            model_name="overseaspo",
            name="ship_to_port",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="สถานที่จัดส่ง (Ship To / Port)",
            ),
        ),
        migrations.AlterField(
            model_name="overseaspo",
            name="pi_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="เลขที่ PI (จากโรงงาน)"
            ),
        ),
    ]
