# Generated by Django 5.1.3 on 2026-04-16 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_product_unit"),
        ("purchasing", "0011_overseaspo_po_number_overseaspo_ship_to_port_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="overseaspoitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.product",
                verbose_name="อ้างอิงรหัสสินค้า (คลัง)",
            ),
        ),
    ]
