# Generated by Django 4.2.30 on 2026-09-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0012_overseaspoitem_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderpayment",
            name="pv_code",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="เลขที่ใบคุมจ่าย (PV)",
            ),
        ),
    ]
