# Generated by Django 5.1.3 on 2026-06-08 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hr", "0013_salesgroup_flat_rate_amount"),
        ("inventory", "0015_subcategory_alter_product_category_and_more"),
        ("master_data", "0017_companyinfo_address_en_alter_companyinfo_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolarJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        verbose_name="เลขที่ใบสั่งงาน (Solar Job)",
                    ),
                ),
                (
                    "labor_cost_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="งบประมาณค่าช่าง (ที่ Center กำหนด)",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="วันที่เริ่มงาน"),
                ),
                (
                    "expected_finish_date",
                    models.DateField(blank=True, null=True, verbose_name="กำหนดเสร็จ"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "ร่าง (รอรับงาน)"),
                            ("PREPARING", "Center กำลังเตรียมของ/จัดช่าง"),
                            ("IN_PROGRESS", "กำลังดำเนินการติดตั้ง"),
                            ("COMPLETED", "ติดตั้งเสร็จสมบูรณ์"),
                            ("CANCELLED", "ยกเลิก"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="สถานะงาน",
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, verbose_name="รายละเอียด/หมายเหตุ"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="master_data.customer",
                        verbose_name="ลูกค้า",
                    ),
                ),
                (
                    "package_sold",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solar_packages",
                        to="inventory.product",
                        verbose_name="แพ็กเกจที่ขาย (FG)",
                    ),
                ),
                (
                    "salesperson",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solar_sales",
                        to="hr.employee",
                        verbose_name="พนักงานขาย",
                    ),
                ),
                (
                    "technician_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.department",
                        verbose_name="ทีมช่างติดตั้ง",
                    ),
                ),
            ],
            options={
                "verbose_name": "ใบสั่งงานโซล่า (Solar Job)",
                "verbose_name_plural": "1. จัดการใบสั่งงานโซล่า",
            },
        ),
        migrations.CreateModel(
            name="SolarExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expense_type",
                    models.CharField(
                        choices=[
                            ("SALES_TRAVEL", "ค่าเดินทางสำรวจหน้างาน (เซลส์)"),
                            ("TECH_TRAVEL", "ค่าเดินทางติดตั้ง (ช่าง)"),
                            ("TECH_LABOR", "ค่าเบิกจ่ายค่าแรงติดตั้ง (ช่าง)"),
                            ("OTHER", "ค่าใช้จ่ายอื่นๆ"),
                        ],
                        max_length=20,
                        verbose_name="ประเภทค่าใช้จ่าย",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="รายละเอียดเพิ่มเติม"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="จำนวนเงินที่เบิก"
                    ),
                ),
                (
                    "receipt_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="solar_expenses/%Y/%m/",
                        verbose_name="รูปสลิป/ใบเสร็จ",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "รอตรวจสอบ"),
                            ("APPROVED", "บัญชีอนุมัติแล้ว"),
                            ("REJECTED", "ไม่อนุมัติ"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="สถานะการอนุมัติ",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_solar_expenses",
                        to="hr.employee",
                        verbose_name="ผู้อนุมัติ (บัญชี)",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.employee",
                        verbose_name="ผู้ตั้งเบิก",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="solar_jobs.solarjob",
                        verbose_name="อ้างอิงใบสั่งงาน (SOL)",
                    ),
                ),
            ],
            options={
                "verbose_name": "รายการตั้งเบิกโซล่า",
                "verbose_name_plural": "2. รายการตั้งเบิกค่าใช้จ่าย",
            },
        ),
        migrations.CreateModel(
            name="SolarJobMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=10,
                        verbose_name="จำนวนที่เบิก",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="ต้นทุนต่อหน่วย (ณ วันที่เบิก)",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="solar_jobs.solarjob",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.product",
                        verbose_name="วัตถุดิบ (RM)",
                    ),
                ),
            ],
            options={
                "verbose_name": "รายการเบิกวัตถุดิบโซล่า",
                "verbose_name_plural": "รายการเบิกวัตถุดิบโซล่า",
            },
        ),
    ]
