# Generated by Django 5.1.3 on 2026-06-11 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0013_salesgroup_flat_rate_amount"),
        ("solar_jobs", "0001_initial"),
        ("solar_sales", "0002_solarproductcategory_solarrawmaterialcategory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solarjob",
            name="expected_finish_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="กำหนดเสร็จ (dd/mm/yyyy)"
            ),
        ),
        migrations.AlterField(
            model_name="solarjob",
            name="package_sold",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solar_jobs",
                to="solar_sales.solarproduct",
                verbose_name="แพ็กเกจที่ขาย (FG)",
            ),
        ),
        migrations.AlterField(
            model_name="solarjob",
            name="salesperson",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solar_sales_jobs",
                to="hr.employee",
                verbose_name="พนักงานขาย",
            ),
        ),
        migrations.AlterField(
            model_name="solarjob",
            name="start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="วันที่เริ่มงาน (dd/mm/yyyy)"
            ),
        ),
        migrations.AlterField(
            model_name="solarjobmaterial",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="solar_sales.solarproduct",
                verbose_name="วัตถุดิบ (RM)",
            ),
        ),
    ]
