# Generated by Django 5.1.3 on 2026-07-27 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar_jobs", "0002_alter_solarjob_expected_finish_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubcontractorTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="ชื่อทีมรับเหมา / ชื่อบริษัท"
                    ),
                ),
                (
                    "leader_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="ชื่อหัวหน้าช่าง"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="เบอร์ติดต่อ"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="สถานะรับงาน"),
                ),
                (
                    "note",
                    models.TextField(blank=True, verbose_name="หมายเหตุ / ความเชี่ยวชาญ"),
                ),
            ],
            options={
                "verbose_name": "ทีมช่างรับเหมาโซล่า",
                "verbose_name_plural": "ฐานข้อมูลทีมช่างรับเหมา",
            },
        ),
        migrations.AlterField(
            model_name="solarjob",
            name="technician_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="solar_jobs.subcontractorteam",
                verbose_name="ทีมช่างติดตั้ง",
            ),
        ),
    ]
