# Generated by Django 4.2.30 on 2026-08-02 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("solar_sales", "0005_solarquotation_deposit_date_and_more"),
        ("solar_jobs", "0003_subcontractorteam_alter_solarjob_technician_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="solarjob",
            name="quotation_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="center_jobs",
                to="solar_sales.solarquotation",
                verbose_name="ใบเสนอราคาอ้างอิง",
            ),
        ),
    ]
