# Generated by Django 4.2.30 on 2026-08-26 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("solar_inventory", "0001_initial"),
        ("solar_jobs", "0004_solarjob_quotation_ref"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solarjob",
            name="package_sold",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solar_jobs",
                to="solar_inventory.solarproduct",
                verbose_name="แพ็กเกจที่ขาย (FG)",
            ),
        ),
        migrations.AlterField(
            model_name="solarjobmaterial",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="solar_inventory.solarproduct",
                verbose_name="วัตถุดิบ (RM)",
            ),
        ),
    ]
