# Generated by Django 4.2.30 on 2026-08-26 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("solar_inventory", "0002_solarstandardbom"),
        ("solar_jobs", "0005_alter_solarjob_package_sold_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolarJobBOM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "planned_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=10,
                        verbose_name="จำนวนตามแผน (BOM)",
                    ),
                ),
                (
                    "actual_used_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="จำนวนที่เบิกใช้จริง",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="ต้นทุนต่อหน่วย (ณ วันที่เบิก)",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_boms",
                        to="solar_jobs.solarjob",
                        verbose_name="อ้างอิงใบสั่งงาน",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        limit_choices_to={"product_type": "RM"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="solar_inventory.solarproduct",
                        verbose_name="วัตถุดิบ (RM)",
                    ),
                ),
            ],
            options={
                "verbose_name": "รายการเบิกวัตถุดิบเฉพาะงาน (Job BOM)",
                "verbose_name_plural": "รายการเบิกวัตถุดิบเฉพาะงาน",
            },
        ),
        migrations.DeleteModel(
            name="SolarJobMaterial",
        ),
    ]
