# Generated by Django 4.2.30 on 2026-08-28 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("solar_inventory", "0002_solarstandardbom"),
        ("hr", "0014_position_approval_authority_position_description"),
        ("solar_jobs", "0006_solarjobbom_delete_solarjobmaterial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolarPurchasePreparation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        verbose_name="เลขที่ใบเตรียมสั่งซื้อ (Solar PPO)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "รอจัดซื้อดำเนินการ"), ("ORDERED", "สั่งซื้อแล้ว")],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.employee",
                        verbose_name="ผู้จัดทำ (สโตร์)",
                    ),
                ),
            ],
            options={
                "verbose_name": "ใบเตรียมสั่งซื้อโซล่า (Solar PPO)",
                "verbose_name_plural": "ใบเตรียมสั่งซื้อโซล่า (Solar PPO)",
            },
        ),
        migrations.AlterField(
            model_name="solarjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "ร่าง (รอรับงาน)"),
                    ("PREPARING", "Center กำลังเตรียมของ/จัดช่าง"),
                    ("WAITING_STORE", "รอสโตร์จ่ายของ (เบิกวัสดุ)"),
                    ("WAITING_PURCHASE", "รอจัดซื้อสั่งของ (ของขาด)"),
                    ("IN_PROGRESS", "กำลังดำเนินการติดตั้ง"),
                    ("COMPLETED", "ติดตั้งเสร็จสมบูรณ์"),
                    ("CANCELLED", "ยกเลิก"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="สถานะงาน",
            ),
        ),
        migrations.CreateModel(
            name="SolarPurchasePreparationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_needed",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="จำนวนที่ต้องการสั่งเพิ่ม",
                    ),
                ),
                (
                    "ppo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="solar_jobs.solarpurchasepreparation",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solar_inventory.solarproduct",
                        verbose_name="วัสดุที่ขาด",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="solarpurchasepreparation",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ppos",
                to="solar_jobs.solarjob",
                verbose_name="อ้างอิงใบสั่งงาน (JOB)",
            ),
        ),
    ]
