# Generated by Django 4.2.30 on 2026-09-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar_jobs", "0007_solarpurchasepreparation_alter_solarjob_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solarjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "ร่าง (รอรับงาน)"),
                    ("PREPARING", "Center กำลังเตรียมของ/จัดช่าง"),
                    ("WAITING_STORE", "รอสโตร์จ่ายของ (เบิกวัสดุ)"),
                    ("WAITING_PURCHASE", "รอจัดซื้อสั่งของ (ของขาด)"),
                    ("IN_PROGRESS", "กำลังดำเนินการติดตั้ง"),
                    ("COMPLETED", "ติดตั้งเสร็จสมบูรณ์"),
                    ("CLOSED", "เปิดบิล/จัดเก็บแล้ว (Archived)"),
                    ("CANCELLED", "ยกเลิก"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="สถานะงาน",
            ),
        ),
    ]
