# Generated by Django 4.2.30 on 2026-09-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar_jobs", "0008_alter_solarjob_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="solarjob",
            name="has_unsent_requisition",
            field=models.BooleanField(
                default=False, verbose_name="มีใบเบิกที่ยังไม่ได้ส่งสโตร์"
            ),
        ),
    ]
