# Generated by Django 4.2.30 on 2026-09-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar_jobs", "0009_solarjob_has_unsent_requisition"),
    ]

    operations = [
        migrations.AddField(
            model_name="solarjob",
            name="is_waiting_purchase",
            field=models.BooleanField(default=False, verbose_name="รอจัดซื้อสั่งของเข้าสโตร์"),
        ),
    ]
