# Generated by Django 4.2.30 on 2026-09-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar_jobs", "0010_solarjob_is_waiting_purchase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solarpurchasepreparation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "รอจัดซื้อดำเนินการ"),
                    ("ORDERED", "สั่งซื้อแล้ว"),
                    ("CANCELLED", "ยกเลิก"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
