# Generated by Django 4.2.30 on 2026-09-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar_jobs", "0011_alter_solarpurchasepreparation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="solarjob",
            name="actual_finish_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="วันที่ติดตั้งเสร็จจริง"
            ),
        ),
    ]
