# Generated by Django 4.2.30 on 2026-09-20 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0014_position_approval_authority_position_description"),
        ("solar_jobs", "0012_solarjob_actual_finish_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolarSurveyClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="เลขที่ใบเบิก"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="ยอดเบิกค่าสำรวจ",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "รอจ่ายเงิน (Pending)"),
                            ("PAID", "จ่ายเงินแล้ว (Paid)"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="สถานะการจ่ายเงิน",
                    ),
                ),
                (
                    "slip_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="solar_survey_slips/%Y/%m/",
                        verbose_name="สลิปหลักฐานการโอน",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่ตั้งเบิก"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="วันที่จ่ายเงิน"
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_claims",
                        to="solar_jobs.solarjob",
                        verbose_name="อ้างอิงใบสั่งงาน (SOL)",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.employee",
                        verbose_name="พนักงานผู้ขอเบิก",
                    ),
                ),
            ],
            options={
                "verbose_name": "ใบเบิกค่าสำรวจหน้างาน (Solar)",
                "verbose_name_plural": "ใบเบิกค่าสำรวจหน้างาน (Solar)",
            },
        ),
        migrations.CreateModel(
            name="SolarOtherExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="เลขที่ใบเบิก"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="รายการที่เบิก"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="ยอดเบิก",
                    ),
                ),
                (
                    "receipt_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="solar_expense_receipts/%Y/%m/",
                        verbose_name="รูปบิลใบเสร็จ/สลิป",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "รอจ่ายเงิน (Pending)"),
                            ("PAID", "จ่ายเงินแล้ว (Paid)"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="สถานะการจ่ายเงิน",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่ตั้งเบิก"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="วันที่จ่ายเงิน"
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="other_expenses",
                        to="solar_jobs.solarjob",
                        verbose_name="อ้างอิงใบสั่งงาน (SOL)",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.employee",
                        verbose_name="พนักงานผู้ขอเบิก",
                    ),
                ),
            ],
            options={
                "verbose_name": "ใบเบิกค่าใช้จ่ายอื่นๆ (Solar)",
                "verbose_name_plural": "ใบเบิกค่าใช้จ่ายอื่นๆ (Solar)",
            },
        ),
        migrations.CreateModel(
            name="SolarInstallClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="เลขที่ใบเบิก"
                    ),
                ),
                (
                    "contractor_name",
                    models.CharField(
                        max_length=150, verbose_name="ชื่อทีมรับเหมา / หัวหน้าช่าง"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="ยอดเบิกค่าติดตั้ง",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "รอจ่ายเงิน (Pending)"),
                            ("PAID", "จ่ายเงินแล้ว (Paid)"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="สถานะการจ่ายเงิน",
                    ),
                ),
                (
                    "slip_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="solar_install_slips/%Y/%m/",
                        verbose_name="สลิปหลักฐานการโอน",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่ตั้งเบิก"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="วันที่จ่ายเงิน"
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="install_claims",
                        to="solar_jobs.solarjob",
                        verbose_name="อ้างอิงใบสั่งงาน (SOL)",
                    ),
                ),
            ],
            options={
                "verbose_name": "ใบเบิกค่าติดตั้ง (Solar)",
                "verbose_name_plural": "ใบเบิกค่าติดตั้ง (Solar)",
            },
        ),
        migrations.CreateModel(
            name="SolarAdvanceLaborClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="เลขที่ใบเบิก"
                    ),
                ),
                (
                    "contractor_name",
                    models.CharField(
                        max_length=150, verbose_name="ชื่อทีมรับเหมา / หัวหน้าช่าง"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="ยอดเบิกสำรองค่าแรง",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "รอจ่ายเงิน (Pending)"),
                            ("PAID", "จ่ายเงินแล้ว (Paid)"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="สถานะการจ่ายเงิน",
                    ),
                ),
                (
                    "slip_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="solar_advance_slips/%Y/%m/",
                        verbose_name="สลิปหลักฐานการโอน",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่ตั้งเบิก"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="วันที่จ่ายเงิน"
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advance_labor_claims",
                        to="solar_jobs.solarjob",
                        verbose_name="อ้างอิงใบสั่งงาน (SOL)",
                    ),
                ),
            ],
            options={
                "verbose_name": "ใบเบิกสำรองค่าแรง (Solar)",
                "verbose_name_plural": "ใบเบิกสำรองค่าแรง (Solar)",
            },
        ),
    ]
