# Generated by Django 5.1.3 on 2026-06-11 15:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hr", "0013_salesgroup_flat_rate_amount"),
        ("master_data", "0017_companyinfo_address_en_alter_companyinfo_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolarCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="หมวดหมู่โซล่าเซลล์"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SolarProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("FG", "แพ็กเกจโซล่า (ขาย)"),
                            ("RM", "วัตถุดิบ/อุปกรณ์ (เบิก/ซื้อ)"),
                        ],
                        default="FG",
                        max_length=2,
                        verbose_name="ประเภทสินค้า",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="รหัสสินค้า (SKU)",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="ชื่อสินค้า/แพ็กเกจ"),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="หน่วยนับ"
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="ราคาทุน",
                    ),
                ),
                (
                    "sell_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="ราคาขาย",
                    ),
                ),
                (
                    "stock_qty",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="จำนวนคงเหลือ",
                    ),
                ),
                (
                    "min_level",
                    models.DecimalField(
                        decimal_places=2,
                        default=5,
                        max_digits=12,
                        verbose_name="จุดสั่งซื้อ (Low Stock)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="เปิดใช้งาน"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="solar_sales.solarcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SolarQuotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="เลขที่ใบเสนอราคาโซล่า"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="วันที่เอกสาร (dd/mm/yyyy)",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="มัดจำ"
                    ),
                ),
                ("is_deposit_paid", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "รออนุมัติ"),
                            ("APPROVED", "อนุมัติแล้ว"),
                            ("CONVERTED", "เปิดบิลขายแล้ว"),
                            ("CANCELLED", "ยกเลิกแล้ว"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="master_data.customer",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.employee",
                        verbose_name="พนักงานขาย",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SolarInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="เลขที่ใบเสร็จโซล่า"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="วันที่เอกสาร (dd/mm/yyyy)",
                    ),
                ),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "balance_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("UNPAID", "ยังไม่ชำระ"), ("PAID", "ชำระแล้ว")],
                        default="UNPAID",
                        max_length=20,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="master_data.customer",
                    ),
                ),
                (
                    "quotation_ref",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="solar_sales.solarquotation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SolarQuotationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="solar_sales.solarproduct",
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="solar_sales.solarquotation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SolarStockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="จำนวน"
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[("IN", "เข้า"), ("OUT", "ออก")],
                        max_length=10,
                        verbose_name="ประเภท",
                    ),
                ),
                (
                    "reference_doc",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="อ้างอิงเอกสาร"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="วันที่ทำรายการ (dd/mm/yyyy)",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solar_sales.solarproduct",
                        verbose_name="สินค้าโซล่า",
                    ),
                ),
            ],
        ),
    ]
