# Generated by Django 5.1.3 on 2026-06-11 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar_sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolarProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="หมวดหมู่แพ็กเกจ/สินค้า (FG)",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "หมวดหมู่สินค้า (FG)",
            },
        ),
        migrations.CreateModel(
            name="SolarRawMaterialCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="หมวดหมู่วัตถุดิบ/อุปกรณ์ (RM)",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "หมวดหมู่วัตถุดิบ (RM)",
            },
        ),
        migrations.AlterField(
            model_name="solarproduct",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="solar_sales.solarproductcategory",
                verbose_name="หมวดหมู่ (FG)",
            ),
        ),
        migrations.AddField(
            model_name="solarproduct",
            name="rm_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="solar_sales.solarrawmaterialcategory",
                verbose_name="หมวดหมู่ (RM)",
            ),
        ),
        migrations.DeleteModel(
            name="SolarCategory",
        ),
    ]
