# Generated by Django 5.1.3 on 2026-06-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar_sales", "0002_solarproductcategory_solarrawmaterialcategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solarquotation",
            name="payment_terms",
            field=models.TextField(
                default="- ชำระเงินมัดจำ 50% ของยอดรวมเพื่อยืนยันการสั่งซื้อ\n- ส่วนที่เหลือชำระก่อนการติดตั้ง",
                verbose_name="เงื่อนไขการชำระเงิน (Payment Terms)",
            ),
        ),
        migrations.AddField(
            model_name="solarquotation",
            name="survey_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="ค่าสำรวจหน้างาน / ค่าจัดส่ง",
            ),
        ),
        migrations.AddField(
            model_name="solarquotation",
            name="valid_until",
            field=models.DateField(
                blank=True, null=True, verbose_name="ยืนยันราคาถึงวันที่ (dd/mm/yyyy)"
            ),
        ),
        migrations.AddField(
            model_name="solarquotation",
            name="vat_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="ยอด VAT 7%"
            ),
        ),
        migrations.AddField(
            model_name="solarquotation",
            name="vat_type",
            field=models.CharField(
                choices=[
                    ("NONE", "ไม่มี VAT"),
                    ("EXCLUDE", "แยก VAT 7%"),
                    ("INCLUDE", "รวม VAT 7%"),
                ],
                default="NONE",
                max_length=10,
                verbose_name="ประเภทภาษี",
            ),
        ),
        migrations.AlterField(
            model_name="solarquotation",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="หักส่วนลด"
            ),
        ),
        migrations.AlterField(
            model_name="solarquotation",
            name="grand_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="ยอดสุทธิ (Grand Total)",
            ),
        ),
        migrations.AlterField(
            model_name="solarquotation",
            name="note",
            field=models.TextField(blank=True, verbose_name="หมายเหตุ"),
        ),
        migrations.AlterField(
            model_name="solarquotation",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="รวมราคาสินค้า"
            ),
        ),
    ]
