# Generated by Django 5.1.3 on 2026-07-26 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar_sales", "0003_solarquotation_payment_terms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solarquotationitem",
            name="item_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ชื่อที่จะแสดงในบิล"
            ),
        ),
        migrations.AlterField(
            model_name="solarquotationitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="solar_sales.solarproduct",
            ),
        ),
    ]
