# Generated by Django 5.1.3 on 2026-07-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar_sales", "0004_solarquotationitem_item_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solarquotation",
            name="deposit_date",
            field=models.DateField(blank=True, null=True, verbose_name="วันที่รับเงินมัดจำ"),
        ),
        migrations.AddField(
            model_name="solarquotation",
            name="deposit_method",
            field=models.CharField(
                default="TRANSFER", max_length=20, verbose_name="ช่องทางรับเงิน"
            ),
        ),
        migrations.AddField(
            model_name="solarquotation",
            name="deposit_slip",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="solar_deposits/",
                verbose_name="สลิปโอนเงิน",
            ),
        ),
        migrations.AddField(
            model_name="solarquotation",
            name="is_deposit_verified",
            field=models.BooleanField(default=False, verbose_name="บัญชีตรวจสอบแล้ว"),
        ),
    ]
