# Generated by Django 4.2.30 on 2026-08-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar_sales", "0005_solarquotation_deposit_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solarquotation",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "รออนุมัติ"),
                    ("APPROVED", "อนุมัติแล้ว"),
                    ("PROCESSING", "ช่างกำลังติดตั้ง"),
                    ("READY", "พร้อมเปิดบิล"),
                    ("CONVERTED", "เปิดบิลขายแล้ว"),
                    ("CANCELLED", "ยกเลิกแล้ว"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
