# Generated by Django 4.2.30 on 2026-08-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar_sales", "0006_alter_solarquotation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="solarquotation",
            name="customer_deposit_signature",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="solar_deposit_signatures/%Y/%m/",
                verbose_name="ลายเซ็นสัญญามัดจำ",
            ),
        ),
        migrations.AddField(
            model_name="solarquotation",
            name="customer_signature",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="solar_customer_signatures/%Y/%m/",
                verbose_name="ลายเซ็นลูกค้า",
            ),
        ),
        migrations.AddField(
            model_name="solarquotation",
            name="deposit_signature_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="เวลาที่เซ็นสัญญามัดจำ"
            ),
        ),
        migrations.AddField(
            model_name="solarquotation",
            name="deposit_signature_token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="solarquotation",
            name="signature_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="เวลาที่ลูกค้าเซ็น"
            ),
        ),
        migrations.AddField(
            model_name="solarquotation",
            name="signature_token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="solarquotation",
            name="vat_type",
            field=models.CharField(
                choices=[
                    ("NONE", "ไม่มี VAT"),
                    ("EXCLUDE", "แยก VAT 7%"),
                    ("INCLUDE", "รวม VAT 7%"),
                ],
                default="INCLUDE",
                max_length=10,
                verbose_name="ประเภทภาษี",
            ),
        ),
    ]
