# Generated by Django 4.2.30 on 2026-08-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar_sales", "0007_solarquotation_customer_deposit_signature_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solarquotation",
            name="deposit_code",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="เลขใบรับเงินมัดจำ"
            ),
        ),
    ]
