# Generated by Django 4.2.30 on 2026-08-16 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0018_companyinfo_solar_logo"),
        ("hr", "0014_position_approval_authority_position_description"),
        ("solar_sales", "0008_solarquotation_deposit_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolarSurveyJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="เลขที่ใบงานสำรวจ"
                    ),
                ),
                ("appointment_date", models.DateTimeField(verbose_name="วันเวลานัดหมาย")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "รอลงพื้นที่"),
                            ("IN_PROGRESS", "กำลังดำเนินการ"),
                            ("COMPLETED", "สำรวจเสร็จสิ้น"),
                            ("CANCELLED", "ยกเลิก"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="สถานะงาน",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, null=True, verbose_name="รายละเอียด/หมายเหตุ"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solar_survey_assigned",
                        to="hr.employee",
                        verbose_name="ผู้มอบหมาย (Admin)",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master_data.customer",
                        verbose_name="ลูกค้า",
                    ),
                ),
                (
                    "surveyor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solar_survey_tasks",
                        to="hr.employee",
                        verbose_name="ผู้สำรวจ (ช่าง)",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SolarSurveyItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_name",
                    models.CharField(max_length=255, verbose_name="รายการวัสดุ/สเปค"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=1, max_digits=10, verbose_name="จำนวน"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="หน่วยนับ"
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="solar_sales.solarsurveyjob",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SolarExpenseClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="เลขที่ใบเบิก"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="ยอดเงินเบิก"
                    ),
                ),
                ("description", models.TextField(verbose_name="รายละเอียดค่าใช้จ่าย")),
                (
                    "slip_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="solar_expenses/",
                        verbose_name="รูปสลิป/ใบเสร็จ",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "รอหัวหน้าอนุมัติ"),
                            ("APPROVED", "อนุมัติแล้ว (รอบัญชีจ่าย)"),
                            ("PAID", "จ่ายเงินแล้ว"),
                            ("REJECTED", "ไม่อนุมัติ"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="สถานะ",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solar_expenses_approved",
                        to="hr.employee",
                        verbose_name="ผู้อนุมัติ (หัวหน้า/บัญชี)",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solar_expenses_requested",
                        to="hr.employee",
                        verbose_name="ผู้ขอเบิก",
                    ),
                ),
                (
                    "survey_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="solar_sales.solarsurveyjob",
                        verbose_name="อ้างอิงใบงานสำรวจ",
                    ),
                ),
            ],
        ),
    ]
