# Generated by Django 4.2.30 on 2026-08-16 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0018_companyinfo_solar_logo"),
        ("solar_sales", "0009_solarsurveyjob_solarsurveyitem_solarexpenseclaim"),
    ]

    operations = [
        migrations.AddField(
            model_name="solarsurveyjob",
            name="walkin_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="ชื่อลูกค้า (Walk-in)"
            ),
        ),
        migrations.AddField(
            model_name="solarsurveyjob",
            name="walkin_phone",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="เบอร์ติดต่อ (Walk-in)"
            ),
        ),
        migrations.AlterField(
            model_name="solarsurveyjob",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="master_data.customer",
                verbose_name="ลูกค้า",
            ),
        ),
    ]
