# Generated by Django 4.2.30 on 2026-08-19 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("solar_sales", "0010_solarsurveyjob_walkin_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolarExpenseSlip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="solar_expenses/slips/", verbose_name="รูปสลิป/ใบเสร็จ"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slips",
                        to="solar_sales.solarexpenseclaim",
                    ),
                ),
            ],
        ),
    ]
