# Generated by Django 4.2.30 on 2026-08-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar_sales", "0011_solarexpenseslip"),
    ]

    operations = [
        migrations.AddField(
            model_name="solarexpenseclaim",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="วันที่โอนเงิน"),
        ),
        migrations.AddField(
            model_name="solarexpenseclaim",
            name="transfer_slip",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="solar_expenses/transfers/",
                verbose_name="สลิปโอนเงินให้ช่าง",
            ),
        ),
    ]
