# Generated by Django 4.2.30 on 2026-08-26 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("solar_jobs", "0005_alter_solarjob_package_sold_and_more"),
        ("solar_inventory", "0001_initial"),
        ("solar_sales", "0012_solarexpenseclaim_paid_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solarstockmovement",
            name="product",
        ),
        migrations.AlterField(
            model_name="solarquotationitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="solar_inventory.solarproduct",
            ),
        ),
        migrations.DeleteModel(
            name="SolarProduct",
        ),
        migrations.DeleteModel(
            name="SolarProductCategory",
        ),
        migrations.DeleteModel(
            name="SolarRawMaterialCategory",
        ),
        migrations.DeleteModel(
            name="SolarStockMovement",
        ),
    ]
