# Generated by Django 4.2.30 on 2026-09-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar_sales", "0013_remove_solarstockmovement_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solarinvoice",
            name="payment_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="ยอดรับชำระล่าสุด"
            ),
        ),
        migrations.AddField(
            model_name="solarinvoice",
            name="payment_date",
            field=models.DateField(blank=True, null=True, verbose_name="วันที่รับชำระล่าสุด"),
        ),
        migrations.AddField(
            model_name="solarinvoice",
            name="payment_method",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="ช่องทางชำระล่าสุด"
            ),
        ),
        migrations.AddField(
            model_name="solarinvoice",
            name="payment_slip",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="solar_invoice_payments/",
                verbose_name="สลิปรับชำระเงินล่าสุด",
            ),
        ),
        migrations.AlterField(
            model_name="solarinvoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNPAID", "ยังไม่ชำระ"),
                    ("PENDING", "รอวางบิล"),
                    ("PENDING_VERIFY", "รอบัญชีตรวจสอบ"),
                    ("PAID", "ชำระแล้ว"),
                ],
                default="UNPAID",
                max_length=20,
            ),
        ),
    ]
