# Generated by Django 4.2.30 on 2026-09-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar_sales", "0014_solarinvoice_payment_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solarquotation",
            name="vat_type",
            field=models.CharField(
                choices=[("INCLUDE", "รวม VAT 7%")],
                default="INCLUDE",
                max_length=10,
                verbose_name="ประเภทภาษี",
            ),
        ),
    ]
