# Generated by Django 4.2.30 on 2026-09-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar_sales", "0016_solarcommissionclaim_solarcommissionticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="solarcommissionclaim",
            name="bank_account",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="เลขที่บัญชี"
            ),
        ),
        migrations.AddField(
            model_name="solarcommissionclaim",
            name="bank_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ธนาคารที่รับเงิน"
            ),
        ),
    ]
