# Generated by Django 4.2.30 on 2026-09-13 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar_sales", "0017_solarcommissionclaim_bank_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solarcommissionclaim",
            name="account_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="ชื่อบัญชีธนาคาร"
            ),
        ),
    ]
