# Generated by Django 5.1.3 on 2026-06-08 14:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hr", "0013_salesgroup_flat_rate_amount"),
        ("inventory", "0015_subcategory_alter_product_category_and_more"),
        ("master_data", "0017_companyinfo_address_en_alter_companyinfo_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolarPurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="เลขที่ใบสั่งซื้อโซล่า (POS)"
                    ),
                ),
                (
                    "supplier_name_free_text",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="ชื่อร้านค้า (กรณีเร่งด่วน/ไม่อยู่ในระบบ)",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="วันที่สั่งซื้อ"
                    ),
                ),
                (
                    "expected_date",
                    models.DateField(blank=True, null=True, verbose_name="กำหนดรับของ"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="ยอดรวมสุทธิ",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "ร่าง (รอผู้จัดการอนุมัติ)"),
                            ("APPROVED", "อนุมัติแล้ว (ดำเนินการสั่งซื้อ)"),
                            ("CANCELLED", "ยกเลิก"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="สถานะเอกสาร",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "รอชำระเงิน"),
                            ("DEPOSIT", "จ่ายมัดจำแล้ว"),
                            ("PAID", "ชำระครบแล้ว"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="สถานะชำระเงิน",
                    ),
                ),
                (
                    "receipt_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "รอรับเข้าคลัง"),
                            ("PARTIAL", "รับของบางส่วน"),
                            ("COMPLETED", "รับของครบถ้วน"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="สถานะรับของเข้าคลัง",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="หมายเหตุ")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.employee",
                        verbose_name="ผู้จัดซื้อ",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="master_data.supplier",
                        verbose_name="ผู้ขาย (Supplier)",
                    ),
                ),
            ],
            options={
                "verbose_name": "ใบสั่งซื้อโซล่า (POS)",
                "verbose_name_plural": "จัดการใบสั่งซื้อโซล่า",
            },
        ),
        migrations.CreateModel(
            name="SolarPurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_name_free_text",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="ชื่อสินค้า (กรณีด่วน/ไม่มีรหัสคลัง)",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=10,
                        verbose_name="จำนวนที่สั่ง",
                    ),
                ),
                (
                    "received_qty",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="จำนวนที่รับเข้าคลังแล้ว",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="ราคาต่อหน่วย",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="รวมเป็นเงิน",
                    ),
                ),
                (
                    "po",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="solar_purchasing.solarpurchaseorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.product",
                        verbose_name="รหัสวัตถุดิบ (จากคลัง)",
                    ),
                ),
            ],
        ),
    ]
