# Generated by Django 4.2.30 on 2026-08-28 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("solar_inventory", "0002_solarstandardbom"),
        ("solar_purchasing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solarpurchaseorderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="solar_inventory.solarproduct",
                verbose_name="รหัสวัตถุดิบ (จากคลังโซล่า)",
            ),
        ),
    ]
