# Generated by Django 4.2.30 on 2026-09-23 04:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("solar_purchasing", "0002_alter_solarpurchaseorderitem_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolarPurchaseOrderPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pv_code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="เลขที่ใบคุมจ่าย (PV)",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="วันที่ชำระเงิน"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="ยอดชำระ"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        default="โอนเงินผ่านธนาคาร",
                        max_length=50,
                        verbose_name="ช่องทางการชำระ",
                    ),
                ),
                (
                    "slip_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="solar_po_payments/%Y/%m/",
                        verbose_name="สลิปโอนเงิน",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="หมายเหตุ")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "po",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="solar_purchasing.solarpurchaseorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "ประวัติการชำระเงิน PO โซล่า",
                "verbose_name_plural": "ประวัติการชำระเงิน PO โซล่า",
            },
        ),
    ]
