# Generated by Django 4.2.30 on 2026-08-26 03:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SolarProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("FG", "แพ็กเกจโซล่า (ขาย)"),
                            ("RM", "วัตถุดิบ/อุปกรณ์ (เบิก/ซื้อ)"),
                        ],
                        default="FG",
                        max_length=2,
                        verbose_name="ประเภทสินค้า",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="รหัสสินค้า (SKU)",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="ชื่อสินค้า/แพ็กเกจ"),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="หน่วยนับ"
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="ราคาทุน",
                    ),
                ),
                (
                    "sell_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="ราคาขาย",
                    ),
                ),
                (
                    "stock_qty",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="จำนวนคงเหลือ",
                    ),
                ),
                (
                    "min_level",
                    models.DecimalField(
                        decimal_places=2,
                        default=5,
                        max_digits=12,
                        verbose_name="จุดสั่งซื้อ (Low Stock)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="เปิดใช้งาน"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SolarProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="หมวดหมู่แพ็กเกจ/สินค้า (FG)",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "หมวดหมู่สินค้า (FG)",
            },
        ),
        migrations.CreateModel(
            name="SolarRawMaterialCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="หมวดหมู่วัตถุดิบ/อุปกรณ์ (RM)",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "หมวดหมู่วัตถุดิบ (RM)",
            },
        ),
        migrations.CreateModel(
            name="SolarStockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="จำนวน"
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[("IN", "เข้า"), ("OUT", "ออก")],
                        max_length=10,
                        verbose_name="ประเภท",
                    ),
                ),
                (
                    "reference_doc",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="อ้างอิงเอกสาร"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="วันที่ทำรายการ"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solar_inventory.solarproduct",
                        verbose_name="สินค้าโซล่า",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="solarproduct",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="solar_inventory.solarproductcategory",
                verbose_name="หมวดหมู่ (FG)",
            ),
        ),
        migrations.AddField(
            model_name="solarproduct",
            name="rm_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="solar_inventory.solarrawmaterialcategory",
                verbose_name="หมวดหมู่ (RM)",
            ),
        ),
    ]
