# Generated by Django 4.2.30 on 2026-08-26 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("solar_inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolarStandardBOM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=10,
                        verbose_name="จำนวนที่ใช้ต่อ 1 แพ็กเกจ",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="หมายเหตุ"
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        limit_choices_to={"product_type": "FG"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standard_boms",
                        to="solar_inventory.solarproduct",
                        verbose_name="แพ็กเกจสินค้า (FG)",
                    ),
                ),
                (
                    "raw_material",
                    models.ForeignKey(
                        limit_choices_to={"product_type": "RM"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_in_standard_boms",
                        to="solar_inventory.solarproduct",
                        verbose_name="วัตถุดิบ (RM)",
                    ),
                ),
            ],
            options={
                "verbose_name": "สูตรการผลิตมาตรฐาน (Standard BOM)",
                "verbose_name_plural": "สูตรการผลิตมาตรฐาน",
            },
        ),
    ]
