# Generated by Django 4.2.30 on 2026-10-03 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("solar_inventory", "0002_solarstandardbom"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolarInventoryDoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_no",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="เลขที่เอกสาร",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("GR", "ใบรับสินค้า (Goods Receipt)"),
                            ("GI", "ใบเบิกสินค้า (Goods Issue)"),
                        ],
                        max_length=2,
                        verbose_name="ประเภทเอกสาร",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="อ้างอิงอื่นๆ (เช่น ใบส่งของ, PO)",
                    ),
                ),
                (
                    "slip_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="solar_receipts/%Y/%m/",
                        verbose_name="รูปใบส่งของ/รับของ",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="หมายเหตุ")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="วันที่เอกสาร"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ทำรายการ",
                    ),
                ),
            ],
            options={
                "verbose_name": "เอกสารคลังโซล่าเซลล์",
                "verbose_name_plural": "เอกสารคลังโซล่าเซลล์ (Docs)",
            },
        ),
        migrations.AddField(
            model_name="solarstockmovement",
            name="doc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movements",
                to="solar_inventory.solarinventorydoc",
                verbose_name="เลขที่เอกสาร",
            ),
        ),
    ]
