# Generated by Django 4.2.30 on 2026-10-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar_inventory", "0003_solarinventorydoc_solarstockmovement_doc"),
    ]

    operations = [
        migrations.AddField(
            model_name="solarproduct",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="solar_products/",
                verbose_name="รูปภาพสินค้า",
            ),
        ),
    ]
