# Generated by Django 5.2.9 on 2026-01-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_th",
                    models.CharField(max_length=200, verbose_name="ชื่อบริษัท (ไทย)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="ชื่อบริษัท (อังกฤษ)"
                    ),
                ),
                ("tax_id", models.CharField(max_length=20, verbose_name="เลขผู้เสียภาษี")),
                (
                    "branch",
                    models.CharField(
                        default="สำนักงานใหญ่", max_length=50, verbose_name="สาขา"
                    ),
                ),
                ("address", models.TextField(verbose_name="ที่อยู่")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="เบอร์โทร"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="อีเมล"),
                ),
                ("website", models.URLField(blank=True, verbose_name="เว็บไซต์")),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="company/", verbose_name="โลโก้"
                    ),
                ),
                (
                    "signature",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="company/",
                        verbose_name="ลายเซ็น/ตราประทับ",
                    ),
                ),
            ],
            options={
                "verbose_name": "1. ข้อมูลบริษัท",
                "verbose_name_plural": "1. ตั้งค่าข้อมูลบริษัท",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="รหัสลูกค้า"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="ชื่อลูกค้า/บริษัท")),
                (
                    "tax_id",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="เลขผู้เสียภาษี"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=100, verbose_name="ผู้ติดต่อ"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="เบอร์โทร"),
                ),
                ("address", models.TextField(blank=True, verbose_name="ที่อยู่")),
                (
                    "credit_term",
                    models.IntegerField(default=0, verbose_name="เครดิต (วัน)"),
                ),
            ],
            options={
                "verbose_name": "2. ฐานข้อมูลลูกค้า",
                "verbose_name_plural": "2. จัดการลูกค้า (Debtors)",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="รหัสผู้ขาย"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="ชื่อร้านค้า/บริษัท")),
                (
                    "tax_id",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="เลขผู้เสียภาษี"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=100, verbose_name="ผู้ติดต่อ"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="เบอร์โทร"),
                ),
                ("address", models.TextField(blank=True, verbose_name="ที่อยู่")),
            ],
            options={
                "verbose_name": "3. ฐานข้อมูลผู้ขาย",
                "verbose_name_plural": "3. จัดการผู้ขาย (Creditors)",
            },
        ),
    ]
