# Generated by Django 5.1.3 on 2026-01-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinfo",
            name="login_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="company/",
                verbose_name="รูปหน้า Login (ควรเป็น PNG พื้นใส)",
            ),
        ),
    ]
