# Generated by Django 5.1.3 on 2026-01-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0002_companyinfo_login_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinfo",
            name="navbar_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="company/",
                verbose_name="รูปบนแถบเมนู (Navbar)",
            ),
        ),
    ]
