# Generated by Django 5.1.3 on 2026-01-07 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0003_companyinfo_navbar_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="ชื่อแผนก")),
            ],
            options={
                "verbose_name": "แผนก",
                "verbose_name_plural": "2.1 แผนก (Departments)",
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="ชื่อตำแหน่ง")),
                (
                    "level",
                    models.IntegerField(
                        default=1, verbose_name="ระดับ (1=พนักงาน, 9=ผู้บริหาร)"
                    ),
                ),
            ],
            options={
                "verbose_name": "ตำแหน่ง",
                "verbose_name_plural": "2.2 ตำแหน่ง (Positions)",
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="หมวดหมู่สินค้า")),
            ],
            options={
                "verbose_name_plural": "5.2 หมวดหมู่สินค้า",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, verbose_name="หน่วยนับ (เช่น ชิ้น, กล่อง)"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "5.1 หน่วยนับ",
            },
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={
                "verbose_name": "ลูกค้า",
                "verbose_name_plural": "3. ฐานข้อมูลลูกค้า (Debtors)",
            },
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={
                "verbose_name": "ผู้ขาย",
                "verbose_name_plural": "4. ฐานข้อมูลผู้ขาย (Creditors)",
            },
        ),
        migrations.RemoveField(
            model_name="customer",
            name="contact_person",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="contact_person",
        ),
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="อีเมล"),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="login_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="company/",
                verbose_name="รูปหน้า Login (ใหญ่)",
            ),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="company/",
                verbose_name="โลโก้เอกสาร (Square)",
            ),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="navbar_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="company/",
                verbose_name="โลโก้บนแถบเมนู (แนวนอน)",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="credit_term",
            field=models.IntegerField(default=30, verbose_name="เครดิต (วัน)"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=200, verbose_name="ชื่อลูกค้า"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="name",
            field=models.CharField(max_length=200, verbose_name="ชื่อผู้ขาย"),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="รหัสสินค้า (SKU)"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="ชื่อสินค้า")),
                (
                    "price_buy",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="ราคาซื้อมาตรฐาน",
                    ),
                ),
                (
                    "price_sell",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="ราคาขายมาตรฐาน",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="ใช้งานอยู่"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="master_data.productcategory",
                        verbose_name="หมวดหมู่",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="master_data.unit",
                        verbose_name="หน่วยนับ",
                    ),
                ),
            ],
            options={
                "verbose_name": "สินค้า",
                "verbose_name_plural": "5. ฐานข้อมูลสินค้า (Products)",
            },
        ),
    ]
