# Generated by Django 5.1.3 on 2026-01-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0004_department_position_productcategory_unit_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.DeleteModel(
            name="Position",
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="unit",
        ),
        migrations.AlterModelOptions(
            name="companyinfo",
            options={
                "verbose_name": "ข้อมูลบริษัท",
                "verbose_name_plural": "1. ตั้งค่าข้อมูลบริษัท",
            },
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={
                "verbose_name": "ลูกค้า",
                "verbose_name_plural": "2. ฐานข้อมูลลูกค้า (Debtors)",
            },
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={
                "verbose_name": "ผู้ขาย",
                "verbose_name_plural": "3. ฐานข้อมูลผู้ขาย (Creditors)",
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="points",
            field=models.IntegerField(default=0, verbose_name="คะแนนสะสม"),
        ),
        migrations.AddField(
            model_name="supplier",
            name="contact_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="ชื่อผู้ติดต่อ"),
        ),
        migrations.DeleteModel(
            name="ProductCategory",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="Unit",
        ),
    ]
