# Generated by Django 5.1.3 on 2026-01-11 11:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0005_delete_department_delete_position_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_th", models.CharField(max_length=150, verbose_name="ชื่อภาษาไทย")),
                (
                    "name_en",
                    models.CharField(max_length=150, verbose_name="ชื่อภาษาอังกฤษ"),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="companyinfo",
            options={"verbose_name_plural": "1. ตั้งค่าข้อมูลบริษัท"},
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "ลูกค้า",
                "verbose_name_plural": "2. ฐานข้อมูลลูกค้า",
            },
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={"verbose_name": "ผู้ขาย", "verbose_name_plural": "3. ฐานข้อมูลผู้ขาย"},
        ),
        migrations.RemoveField(
            model_name="customer",
            name="points",
        ),
        migrations.AddField(
            model_name="customer",
            name="branch",
            field=models.CharField(
                blank=True, default="สำนักงานใหญ่", max_length=100, verbose_name="สาขา"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="contact_person",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ชื่อผู้ติดต่อ"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="credit_limit",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="วงเงินเครดิต"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="district",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="อำเภอ/เขต"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="สถานะใช้งาน"),
        ),
        migrations.AddField(
            model_name="customer",
            name="line_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Line ID"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="location",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="พิกัด GPS / Maps Link",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="note",
            field=models.TextField(blank=True, null=True, verbose_name="หมายเหตุ"),
        ),
        migrations.AddField(
            model_name="customer",
            name="province",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="จังหวัด"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="sub_district",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ตำบล/แขวง"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="zip_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="รหัสไปรษณีย์"
            ),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="login_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="company/", verbose_name="รูปหน้า Login"
            ),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="company/", verbose_name="โลโก้"
            ),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="navbar_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="company/", verbose_name="โลโก้บนแถบเมนู"
            ),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="signature",
            field=models.ImageField(
                blank=True, null=True, upload_to="company/", verbose_name="ลายเซ็น"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.CharField(max_length=255, verbose_name="ที่อยู่ (เลขที่/หมู่บ้าน/ถนน)"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="code",
            field=models.CharField(
                blank=True, max_length=20, unique=True, verbose_name="รหัสลูกค้า"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="credit_term",
            field=models.IntegerField(default=0, verbose_name="เครดิต (วัน)"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="อีเมล"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=200, verbose_name="ชื่อลูกค้า / บริษัท"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="เบอร์โทรศัพท์"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="tax_id",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="เลขผู้เสียภาษี"
            ),
        ),
        migrations.CreateModel(
            name="Amphure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_th", models.CharField(max_length=150, verbose_name="ชื่อภาษาไทย")),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amphures",
                        to="master_data.province",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tambon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_th", models.CharField(max_length=150, verbose_name="ชื่อภาษาไทย")),
                ("zip_code", models.CharField(max_length=10, verbose_name="รหัสไปรษณีย์")),
                (
                    "amphure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tambons",
                        to="master_data.amphure",
                    ),
                ),
            ],
        ),
    ]
