# Generated by Django 5.1.3 on 2026-01-12 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0006_province_alter_companyinfo_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(
                default="0000000000",
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        "^0\\d{8,9}$", "เบอร์โทรต้องเป็นตัวเลข 9-10 หลักและขึ้นต้นด้วย 0"
                    )
                ],
                verbose_name="เบอร์โทรศัพท์",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customer",
            name="tax_id",
            field=models.CharField(
                blank=True,
                max_length=13,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{13}$", "เลขผู้เสียภาษีต้องเป็นตัวเลข 13 หลัก"
                    )
                ],
                verbose_name="เลขผู้เสียภาษี",
            ),
        ),
    ]
