# Generated by Django 5.1.3 on 2026-01-23 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0007_alter_customer_phone_alter_customer_tax_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "2. ฐานข้อมูลลูกค้า",
            },
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={"verbose_name_plural": "3. ฐานข้อมูลผู้ขาย"},
        ),
        migrations.RemoveField(
            model_name="companyinfo",
            name="signature",
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="seal",
            field=models.ImageField(
                blank=True, null=True, upload_to="company/", verbose_name="ตราประทับบริษัท"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.CharField(max_length=255, verbose_name="ที่อยู่"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="district",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="อำเภอ"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="location",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="พิกัด GPS"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        "^0\\d{8,9}$", "เบอร์โทรไม่ถูกต้อง"
                    )
                ],
                verbose_name="เบอร์โทรศัพท์",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="sub_district",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ตำบล"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="tax_id",
            field=models.CharField(
                blank=True,
                max_length=13,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{13}$", "ต้องเป็นตัวเลข 13 หลัก"
                    )
                ],
                verbose_name="เลขผู้เสียภาษี",
            ),
        ),
    ]
