# Generated by Django 5.1.3 on 2026-01-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0008_alter_customer_options_alter_supplier_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyinfo",
            name="seal",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="company/",
                verbose_name="ตราประทับบริษัท (Seal)",
            ),
        ),
    ]
