# Generated by Django 5.1.3 on 2026-01-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0009_alter_companyinfo_seal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyinfo",
            name="seal",
        ),
    ]
