# Generated by Django 5.1.3 on 2026-01-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0012_remove_companyinfo_seal"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinfo",
            name="seal",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="company/",
                verbose_name="ตราประทับบริษัท (Seal)",
            ),
        ),
    ]
