# Generated by Django 5.1.3 on 2026-04-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0013_companyinfo_seal"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "origin_branch",
                    models.CharField(
                        choices=[
                            ("บางพระ", "บางพระ (ชลบุรี)"),
                            ("นครปฐม", "นครปฐม"),
                            ("อยุธยา", "อยุธยา"),
                        ],
                        max_length=100,
                        verbose_name="สาขาต้นทาง (ผลิต)",
                    ),
                ),
                (
                    "destination_province",
                    models.CharField(max_length=100, verbose_name="จังหวัดปลายทาง"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="ค่าขนส่งมาตรฐาน"
                    ),
                ),
            ],
            options={
                "verbose_name": "ตั้งค่าเรทค่าขนส่ง",
                "verbose_name_plural": "4. ตั้งค่าเรทค่าขนส่ง",
                "unique_together": {("origin_branch", "destination_province")},
            },
        ),
    ]
