# Generated by Django 5.1.3 on 2026-04-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0014_shippingrate"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="credit_term",
            field=models.IntegerField(default=0, verbose_name="เครดิตเทอม (วัน)"),
        ),
        migrations.AddField(
            model_name="supplier",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="อีเมล"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="address",
            field=models.TextField(blank=True, verbose_name="ที่อยู่ร้านค้า"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="contact_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="ชื่อผู้ติดต่อ (เซลส์)"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="name",
            field=models.CharField(
                max_length=200, verbose_name="ชื่อบริษัท/ร้านค้า (ซัพพลายเออร์)"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="phone",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="เบอร์โทรศัพท์"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="tax_id",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="เลขประจำตัวผู้เสียภาษี"
            ),
        ),
    ]
