# Generated by Django 5.1.3 on 2026-04-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0015_supplier_credit_term_supplier_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinfo",
            name="weekly_job_quota",
            field=models.IntegerField(
                default=25, verbose_name="โควตางานผลิตต่อสัปดาห์ (Jobs)"
            ),
        ),
    ]
