# Generated by Django 5.1.3 on 2026-04-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0016_companyinfo_weekly_job_quota"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinfo",
            name="address_en",
            field=models.TextField(blank=True, verbose_name="ที่อยู่ (อังกฤษ)"),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="address",
            field=models.TextField(verbose_name="ที่อยู่ (ไทย)"),
        ),
    ]
