# Generated by Django 5.1.3 on 2026-07-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0017_companyinfo_address_en_alter_companyinfo_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinfo",
            name="solar_logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="company/",
                verbose_name="โลโก้ (ระบบโซล่าเซลล์)",
            ),
        ),
    ]
