# Generated by Django 4.2.30 on 2026-08-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0018_companyinfo_solar_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinfo",
            name="signature",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="company/",
                verbose_name="รูปลายเซ็นกรรมการ (Signature)",
            ),
        ),
    ]
