# Generated by Django 5.2.9 on 2026-01-04 11:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="ชื่อหมวดหมู่")),
            ],
            options={
                "verbose_name": "1. หมวดหมู่ค่าใช้จ่าย",
                "verbose_name_plural": "1. ตั้งค่าหมวดหมู่จ่าย",
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="รายการ")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="จำนวนเงิน"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="วันที่จ่าย"
                    ),
                ),
                (
                    "slip_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="expenses/",
                        verbose_name="รูปสลิป/ใบเสร็จ",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="หมายเหตุ")),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.expensecategory",
                        verbose_name="หมวดหมู่",
                    ),
                ),
            ],
            options={
                "verbose_name": "2. บันทึกรายจ่าย",
                "verbose_name_plural": "2. รายการรายจ่าย (Expenses)",
            },
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="รายการ")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="จำนวนเงิน"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="วันที่รับ"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="หมายเหตุ")),
                (
                    "pos_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sales.posorder",
                        verbose_name="มาจากบิล POS",
                    ),
                ),
            ],
            options={
                "verbose_name": "3. บันทึกรายรับ",
                "verbose_name_plural": "3. รายการรายรับ (Incomes)",
            },
        ),
    ]
