# Generated by Django 5.1.3 on 2026-01-11 08:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("master_data", "0005_delete_department_delete_position_and_more"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="posorder",
            options={
                "verbose_name": "บิลขายหน้าร้าน (POS)",
                "verbose_name_plural": "ประวัติการขาย POS",
            },
        ),
        migrations.AlterModelOptions(
            name="quotation",
            options={},
        ),
        migrations.RemoveField(
            model_name="posorderitem",
            name="product_name",
        ),
        migrations.RemoveField(
            model_name="quotation",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="quotation",
            name="employee",
        ),
        migrations.RemoveField(
            model_name="quotation",
            name="note",
        ),
        migrations.RemoveField(
            model_name="quotation",
            name="subtotal",
        ),
        migrations.RemoveField(
            model_name="quotation",
            name="tax_amount",
        ),
        migrations.RemoveField(
            model_name="quotation",
            name="valid_until",
        ),
        migrations.RemoveField(
            model_name="quotationitem",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="quotationitem",
            name="description",
        ),
        migrations.RemoveField(
            model_name="quotationitem",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="quotationitem",
            name="unit_price",
        ),
        migrations.AddField(
            model_name="posorder",
            name="is_commission_calculated",
            field=models.BooleanField(default=False, verbose_name="คำนวณคอมฯแล้ว"),
        ),
        migrations.AddField(
            model_name="posorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "รอชำระเงิน"),
                    ("PAID", "ชำระเงินแล้ว"),
                    ("CANCELLED", "ยกเลิก"),
                ],
                default="PAID",
                max_length=20,
                verbose_name="สถานะ",
            ),
        ),
        migrations.AlterField(
            model_name="posorder",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="master_data.customer",
                verbose_name="ลูกค้า",
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="code",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="master_data.customer",
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="grand_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="status",
            field=models.CharField(default="DRAFT", max_length=20),
        ),
        migrations.AlterField(
            model_name="quotationitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.product",
            ),
        ),
    ]
