# Generated by Django 5.1.3 on 2026-01-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_alter_posorder_options_alter_quotation_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="posorderitem",
            name="product_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="ชื่อสินค้า (ณ ตอนขาย)"
            ),
        ),
    ]
