# Generated by Django 5.1.3 on 2026-01-11 10:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0006_commissionlog"),
        ("inventory", "0001_initial"),
        ("master_data", "0005_delete_department_delete_position_and_more"),
        ("sales", "0003_posorderitem_product_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="posorder",
            options={},
        ),
        migrations.AddField(
            model_name="quotation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quotation",
            name="customer_address",
            field=models.TextField(blank=True, verbose_name="ที่อยู่"),
        ),
        migrations.AddField(
            model_name="quotation",
            name="customer_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="ชื่อลูกค้า (ระบุเอง)"
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="customer_phone",
            field=models.CharField(blank=True, max_length=50, verbose_name="เบอร์โทร"),
        ),
        migrations.AddField(
            model_name="quotation",
            name="customer_tax_id",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="เลขผู้เสียภาษี"
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="ส่วนลด"
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="employee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hr.employee",
                verbose_name="ผู้ออกใบเสนอราคา",
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="note",
            field=models.TextField(blank=True, verbose_name="หมายเหตุ"),
        ),
        migrations.AddField(
            model_name="quotation",
            name="shipping_cost",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="ค่าขนส่ง"
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="รวมราคาสินค้า"
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="ภาษีมูลค่าเพิ่ม"
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="valid_until",
            field=models.DateField(blank=True, null=True, verbose_name="ยืนราคาถึงวันที่"),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="รวมเงิน"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="item_name",
            field=models.CharField(
                default="", max_length=200, verbose_name="ชื่อรายการสินค้า"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="quantity",
            field=models.IntegerField(default=1, verbose_name="จำนวน"),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="ราคาต่อหน่วย"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="quotation",
            name="code",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="เลขที่ใบเสนอราคา"
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="master_data.customer",
                verbose_name="ลูกค้า (Link)",
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="วันที่เอกสาร"
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="grand_total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="ยอดสุทธิ"
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "รอยืนยัน"),
                    ("APPROVED", "อนุมัติ/สั่งซื้อแล้ว"),
                    ("REJECTED", "ยกเลิก"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="สถานะ",
            ),
        ),
        migrations.AlterField(
            model_name="quotationitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.product",
                verbose_name="สินค้า",
            ),
        ),
    ]
