# Generated by Django 5.1.3 on 2026-01-23 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0007_alter_attendance_options_alter_commissionlog_options_and_more"),
        ("sales", "0004_alter_posorder_options_quotation_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="วันที่อนุมัติ"),
        ),
        migrations.AddField(
            model_name="quotation",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_quotations",
                to="hr.employee",
                verbose_name="ผู้อนุมัติ",
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "รออนุมัติ"),
                    ("APPROVED", "อนุมัติแล้ว"),
                    ("REJECTED", "ไม่อนุมัติ"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="สถานะ",
            ),
        ),
    ]
