# Generated by Django 5.1.3 on 2026-01-24 15:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0007_alter_attendance_options_alter_commissionlog_options_and_more"),
        ("master_data", "0008_alter_customer_options_alter_supplier_options_and_more"),
        ("sales", "0005_quotation_approved_at_quotation_approved_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotation",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "รออนุมัติ"),
                    ("APPROVED", "อนุมัติแล้ว"),
                    ("CONVERTED", "เปิดบิลขายแล้ว"),
                    ("REJECTED", "ไม่อนุมัติ"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="สถานะ",
            ),
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="เลขที่ใบกำกับภาษี/ใบเสร็จ"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="วันที่เอกสาร"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="ครบกำหนดชำระ"
                    ),
                ),
                (
                    "grand_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="ยอดสุทธิ",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("UNPAID", "ยังไม่ชำระ"), ("PAID", "ชำระแล้ว")],
                        default="UNPAID",
                        max_length=20,
                        verbose_name="สถานะ",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="master_data.customer",
                        verbose_name="ลูกค้า",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.employee",
                        verbose_name="พนักงานขาย",
                    ),
                ),
                (
                    "quotation_ref",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sales.quotation",
                        verbose_name="อ้างอิงใบเสนอราคา",
                    ),
                ),
            ],
        ),
    ]
