# Generated by Django 5.1.3 on 2026-02-08 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0013_companyinfo_seal"),
        ("sales", "0006_alter_quotation_status_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="posorder",
            name="check_bank",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="ธนาคารเช็ค"
            ),
        ),
        migrations.AddField(
            model_name="posorder",
            name="check_number",
            field=models.CharField(blank=True, max_length=50, verbose_name="เลขที่เช็ค"),
        ),
        migrations.AddField(
            model_name="posorder",
            name="customer_address",
            field=models.TextField(blank=True, verbose_name="ที่อยู่"),
        ),
        migrations.AddField(
            model_name="posorder",
            name="customer_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="ชื่อลูกค้า (ระบุเอง)"
            ),
        ),
        migrations.AddField(
            model_name="posorder",
            name="customer_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="เบอร์โทรศัพท์"
            ),
        ),
        migrations.AddField(
            model_name="posorder",
            name="customer_tax_id",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="เลขผู้เสียภาษี"
            ),
        ),
        migrations.AddField(
            model_name="posorder",
            name="transfer_slip",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="pos_slips/%Y/%m/",
                verbose_name="สลิปโอนเงิน",
            ),
        ),
        migrations.AlterField(
            model_name="posorder",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="master_data.customer",
                verbose_name="ลูกค้า (สมาชิก)",
            ),
        ),
        migrations.AlterField(
            model_name="posorder",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "เงินสด"),
                    ("TRANSFER", "โอนเงิน"),
                    ("CHECK", "เช็คธนาคาร"),
                ],
                default="CASH",
                max_length=50,
                verbose_name="วิธีชำระ",
            ),
        ),
    ]
