# Generated by Django 5.1.3 on 2026-03-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0007_posorder_check_bank_posorder_check_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotation",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "รออนุมัติ"),
                    ("APPROVED", "อนุมัติแล้ว"),
                    ("CONVERTED", "เปิดบิลขายแล้ว"),
                    ("REJECTED", "ไม่อนุมัติ"),
                    ("CANCELLED", "ยกเลิกแล้ว"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="สถานะ",
            ),
        ),
    ]
