# Generated by Django 5.1.3 on 2026-03-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0008_alter_quotation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="posorder",
            name="check_slip",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="pos_checks/%Y/%m/",
                verbose_name="รูปถ่ายเช็ค",
            ),
        ),
    ]
