# Generated by Django 5.1.3 on 2026-03-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0009_posorder_check_slip"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="balance_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="ยอดคงค้างชำระ"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="deposit_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="หักมัดจำ"
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="deposit_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="ยอดมัดจำที่รับแล้ว"
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="deposit_date",
            field=models.DateField(blank=True, null=True, verbose_name="วันที่รับมัดจำ"),
        ),
        migrations.AddField(
            model_name="quotation",
            name="deposit_method",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="ช่องทางรับมัดจำ"
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="deposit_slip",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="deposit_slips/%Y/%m/",
                verbose_name="สลิปมัดจำ",
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="is_deposit_paid",
            field=models.BooleanField(default=False, verbose_name="รับมัดจำแล้ว"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNPAID", "ยังไม่ชำระ"),
                    ("PAID", "ชำระแล้ว"),
                    ("PENDING", "รอตรวจสอบ"),
                ],
                default="UNPAID",
                max_length=20,
                verbose_name="สถานะ",
            ),
        ),
    ]
