# Generated by Django 5.1.3 on 2026-03-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0010_invoice_balance_amount_invoice_deposit_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="is_deposit_verified",
            field=models.BooleanField(default=False, verbose_name="บัญชีตรวจสอบมัดจำแล้ว"),
        ),
    ]
