# Generated by Django 5.1.3 on 2026-03-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0011_quotation_is_deposit_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="check_bank",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="ธนาคารเช็ค"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="check_number",
            field=models.CharField(blank=True, max_length=50, verbose_name="เลขที่เช็ค"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="check_slip",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="invoice_checks/%Y/%m/",
                verbose_name="รูปถ่ายเช็ค",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_date",
            field=models.DateField(blank=True, null=True, verbose_name="วันที่ชำระเงิน"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CASH", "เงินสด"),
                    ("TRANSFER", "โอนเงิน"),
                    ("CHECK", "เช็คธนาคาร"),
                ],
                max_length=50,
                null=True,
                verbose_name="วิธีชำระเงิน",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="transfer_slip",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="invoice_slips/%Y/%m/",
                verbose_name="สลิปโอนเงิน",
            ),
        ),
    ]
