# Generated by Django 5.1.3 on 2026-03-22 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0012_invoice_check_bank_invoice_check_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpsaleCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="ชื่อรายการปรับเปลี่ยน/เพิ่มเติม"
                    ),
                ),
                (
                    "default_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="ราคามาตรฐาน"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        default="รายการ",
                        max_length=50,
                        null=True,
                        verbose_name="หน่วยนับ",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="เปิดใช้งาน"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuotationUpsale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="รายการเพิ่มเติม"),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upsales",
                        to="sales.quotation",
                    ),
                ),
            ],
        ),
    ]
