# Generated by Django 5.1.3 on 2026-03-22 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0013_upsalecatalog_quotationupsale"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpsaleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="หมวดหมู่รายการเพิ่มเติม"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="เปิดใช้งาน"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="upsalecatalog",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sales.upsalecategory",
                verbose_name="หมวดหมู่",
            ),
        ),
    ]
