# Generated by Django 5.1.3 on 2026-03-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0014_upsalecategory_upsalecatalog_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="payment_terms",
            field=models.TextField(blank=True, verbose_name="เงื่อนไขการชำระเงิน"),
        ),
    ]
