# Generated by Django 5.1.3 on 2026-04-02 17:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0015_quotation_payment_terms"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoicePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="ยอดชำระ"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "เงินสด"),
                            ("TRANSFER", "โอนเงิน"),
                            ("CHECK", "เช็คธนาคาร"),
                        ],
                        max_length=50,
                        verbose_name="วิธีชำระ",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="วันที่ชำระ"
                    ),
                ),
                (
                    "transfer_slip",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="invoice_slips/%Y/%m/",
                        verbose_name="สลิปโอนเงิน",
                    ),
                ),
                (
                    "check_number",
                    models.CharField(blank=True, max_length=50, verbose_name="เลขที่เช็ค"),
                ),
                (
                    "check_bank",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ธนาคารเช็ค"
                    ),
                ),
                (
                    "check_slip",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="invoice_checks/%Y/%m/",
                        verbose_name="รูปถ่ายเช็ค",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "รอตรวจสอบ"), ("VERIFIED", "ตรวจสอบแล้ว")],
                        default="PENDING",
                        max_length=20,
                        verbose_name="สถานะการตรวจ",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_history",
                        to="sales.invoice",
                        verbose_name="อ้างอิงบิล",
                    ),
                ),
            ],
        ),
    ]
