# Generated by Django 5.1.3 on 2026-04-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0016_invoicepayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="shipping_is_island",
            field=models.BooleanField(default=False, verbose_name="ส่งข้ามเกาะ"),
        ),
        migrations.AddField(
            model_name="quotation",
            name="shipping_is_oversize",
            field=models.BooleanField(
                default=False, verbose_name="ตู้ยาวเกินมาตรฐาน (+1000)"
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="shipping_origin",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="สาขาต้นทาง (ผลิต)"
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="shipping_province",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="จังหวัดปลายทาง"
            ),
        ),
    ]
