# Generated by Django 5.1.3 on 2026-04-20 18:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0012_employee_production_team"),
        ("sales", "0017_quotation_shipping_is_island_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="รหัสลูกค้า (Lead ID)"
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="วันที่ติดต่อล่าสุด"
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=200, verbose_name="ชื่อลูกค้า / โปรไฟล์"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="เบอร์ติดต่อ"
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("FACEBOOK", "🔵 Facebook"),
                            ("LINE", "🟢 LINE / LINE OA"),
                            ("PHONE", "📞 โทรศัพท์ติดต่อ"),
                            ("WALKIN", "🚶 หน้าร้าน / เข้ามาดูงาน"),
                            ("OTHER", "🌐 ช่องทางอื่นๆ"),
                        ],
                        default="LINE",
                        max_length=20,
                        verbose_name="ช่องทางที่ติดต่อเข้ามา",
                    ),
                ),
                (
                    "requirements",
                    models.TextField(
                        blank=True, verbose_name="รายละเอียด/ความต้องการของลูกค้า"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "ติดต่อใหม่ (New)"),
                            ("FOLLOW_UP", "กำลังเจรจา (Follow Up)"),
                            ("QUOTED", "เสนอราคาแล้ว (Quoted)"),
                            ("WON", "ปิดการขายสำเร็จ (Won)"),
                            ("LOST", "ยกเลิก/ไม่สนใจ (Lost)"),
                        ],
                        default="NEW",
                        max_length=20,
                        verbose_name="สถานะลูกค้า",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.employee",
                        verbose_name="พนักงานขายผู้ดูแล",
                    ),
                ),
            ],
        ),
    ]
