# Generated by Django 5.1.3 on 2026-04-20 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0012_employee_production_team"),
        ("sales", "0018_customerlead"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appointment_date",
                    models.DateTimeField(verbose_name="วัน/เวลาที่นัดหมาย"),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("PRE_BOOKED", "นัดหมายล่วงหน้า (Appointment)"),
                            ("WALK_IN", "เข้ามาหน้าร้าน (Walk-in)"),
                        ],
                        default="PRE_BOOKED",
                        max_length=20,
                        verbose_name="ประเภทการติดต่อ",
                    ),
                ),
                (
                    "details",
                    models.TextField(blank=True, verbose_name="รายละเอียด/หมายเหตุ"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "⏳ รอดำเนินการ"),
                            ("COMPLETED", "🤝 สำเร็จ / เข้ามาแล้ว"),
                            ("CANCELLED", "❌ ยกเลิกนัด"),
                            ("NO_SHOW", "👻 ไม่มาตามนัด"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                        verbose_name="สถานะ",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.employee",
                        verbose_name="พนักงานผู้รับผิดชอบ",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="sales.customerlead",
                        verbose_name="ลูกค้ามุ่งหวัง",
                    ),
                ),
            ],
        ),
    ]
