# Generated by Django 5.1.3 on 2026-07-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0019_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="customer_signature",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="customer_signatures/%Y/%m/",
                verbose_name="ลายเซ็นลูกค้า",
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="signature_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="เวลาที่ลูกค้าเซ็น"
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="signature_token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
