# Generated by Django 5.1.3 on 2026-07-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0020_quotation_customer_signature_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="customer_deposit_signature",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="deposit_signatures_contract/%Y/%m/",
                verbose_name="ลายเซ็นสัญญามัดจำ",
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="deposit_signature_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="เวลาที่เซ็นสัญญามัดจำ"
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="deposit_signature_token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
