# Generated by Django 4.2.30 on 2026-08-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0021_quotation_customer_deposit_signature_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="deposit_code",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="เลขที่ใบรับมัดจำ"
            ),
        ),
    ]
