# Generated by Django 4.2.30 on 2026-08-12 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0014_position_approval_authority_position_description"),
        ("sales", "0022_quotation_deposit_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_invoices",
                to="hr.employee",
                verbose_name="ผู้ตรวจสอบรับเงิน",
            ),
        ),
    ]
