# Generated by Django 4.2.30 on 2026-09-16 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0014_position_approval_authority_position_description"),
        ("sales", "0023_invoice_verified_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommissionClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="เลขที่ใบเบิกผลตอบแทน"
                    ),
                ),
                (
                    "claim_type",
                    models.CharField(
                        choices=[("2%", "2% (จากมัดจำ)"), ("3%", "3% (จากปิดบิล)")],
                        max_length=10,
                        verbose_name="ประเภทการเบิก",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="ยอดเงินรวม",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ธนาคารที่รับเงิน",
                    ),
                ),
                (
                    "bank_account",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="เลขที่บัญชี"
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="ชื่อบัญชีธนาคาร",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "รอโอนเงิน"), ("PAID", "โอนเงินแล้ว")],
                        default="PENDING",
                        max_length=20,
                        verbose_name="สถานะ",
                    ),
                ),
                (
                    "transfer_slip",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="commissions_knockdown/",
                        verbose_name="สลิปโอนเงิน",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="วันที่โอนเงิน"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requester",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.employee",
                        verbose_name="ผู้ทำรายการเบิก",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommissionTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="เลขที่ใบคุมสิทธิ์"
                    ),
                ),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[("2%", "2% (จากมัดจำ)"), ("3%", "3% (จากปิดบิล)")],
                        max_length=10,
                        verbose_name="ประเภทสิทธิ์",
                    ),
                ),
                (
                    "base_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="ยอดฐานคำนวณ (หัก 10%)",
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="ยอดผลตอบแทน"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "พร้อมเบิก"),
                            ("CLAIMING", "กำลังตั้งเบิก"),
                            ("PAID", "จ่ายแล้ว"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                        verbose_name="สถานะสิทธิ์",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claim_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="sales.commissionclaim",
                        verbose_name="รวมอยู่ในใบเบิกเลขที่",
                    ),
                ),
                (
                    "invoice_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sales.invoice",
                        verbose_name="อ้างอิงใบแจ้งหนี้",
                    ),
                ),
                (
                    "quotation_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sales.quotation",
                        verbose_name="อ้างอิงใบเสนอราคา",
                    ),
                ),
            ],
        ),
    ]
