# Generated by Django 4.2.30 on 2026-09-19 05:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0024_commissionclaim_commissionticket"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuotationDeposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="เลขที่ใบรับมัดจำ (RVD)"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="ยอดมัดจำที่รับ",
                    ),
                ),
                (
                    "deposit_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="วันที่รับมัดจำ"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="ช่องทางรับมัดจำ",
                    ),
                ),
                (
                    "deposit_slip",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="deposit_slips_v2/%Y/%m/",
                        verbose_name="สลิปมัดจำ",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, verbose_name="บัญชีตรวจสอบมัดจำแล้ว"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deposits",
                        to="sales.quotation",
                        verbose_name="อ้างอิงใบเสนอราคา",
                    ),
                ),
            ],
        ),
    ]
