# Generated by Django 4.2.30 on 2026-09-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0025_quotationdeposit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotationdeposit",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CASH", "เงินสด"),
                    ("TRANSFER", "โอนเงิน"),
                    ("CHECK", "เช็คธนาคาร"),
                ],
                max_length=50,
                null=True,
                verbose_name="ช่องทางรับมัดจำ",
            ),
        ),
    ]
